### ISSUE TITLE
Falcon Post Params

### ISSUE THREAD

**Issue by ZeeshanSultan** [falconry/falcon#1033]
```
import falcon
from falcon_cors import CORS
cors = CORS(allow_all_origins=True)

class TestClass:
    def on_post(self, req, resp):
        print req.params

api = falcon.API(middleware=[cors.middleware])
api.add_route('/test', TestClass())
```

The params is returned as an empty dict.

i've tried it with
`print json.dumps(urlparse.parse_qs(resp.stream.read())`

what's the fix to the real params attribute ?

**Comment by kgriffs** [comment]
Hi @ZeeshanSultan, you can use [RequestOptions.auto_parse_form_urlencoded][1] to configure the framework to automatically parse form params and merge them into query string params (if any) so that they are accessible via `req.params`.

[1]: http://falcon.readthedocs.io/en/stable/api/api.html#RequestOptions.auto_parse_form_urlencoded
