### ISSUE TITLE
Multiple cookies with same name in request returns only one

### ISSUE THREAD

**Issue by gdude2002** [falconry/falcon#1046]
This looks like it could be relatively simple fix, but it would involve changing the cookie API a bit.

If my browser has two cookies set using the same name - let's call this `_csrf` for example - they are both sent to the server. This is the string returned by `req.get_header("Cookie")`:

```
_csrf=2HBpry7fn6OBCIdS2SnFI-jCdQcq3bt0m03gWgCtjRA; _csrf=Oq_o_Lo_dhhDXqZHQ95NhBp8Nvzntx1FUG-2ryAi6nA
```

However, only one of these is made available in `req.cookies`.

It would be preferable to have a method of getting both of these cookies somehow.

**Comment by kgriffs** [comment]
We could potentially add a new method, `get_cookie_values()` to handle this case. How else might this be designed? Happy to take suggestions.

**Comment by nZac** [comment]
Thanks for submitting this Gareth, I think this is a helpful request and I appreciate you taking the time to submit it as an issue.

I don't think this is something that should be supported as I think it breaks that key-value nature of HTTP Cookies. While the [HTTP cookie spec](https://tools.ietf.org/html/rfc6265#section-5.4) does not prohibit it explicitly, it does use the term `set` which, in a mathematical sense are distinct or unique objects.  By adding support for multiple values for a given key, we are no longer working with a set- this would cause deviation from the spec and I do not believe is desirable.

As you have mentioned, you can get the raw value for the `Cookie` header by accessing `req.headers` directly.

To expand on this a bit, by default Werkzueg (the wsgi layer for Flask) uses `MultiDict`'s base class https://github.com/pallets/werkzeug/blob/e378a8f83d7549904abd7ae5b7ac53491a3c76cf/werkzeug/http.py#L997 which is interesting because the feature is there to support the functionality you are requesting (`MultiDict`) however Flask does not use it. 

Here is an example flask app which generates the same result as Falcon (the last value in the cookie header for that key).

```python3
import flask
app = flask.Flask(__name__)

@app.route('/')
def index():
    print(flask.request.cookies)
    return '', 200

if __name__ == '__main__':
    app.run()
```

When I run this HTTP request:

```http
GET / HTTP/1.1
Cookie: _csrf=2HBpry7fn6OBCIdS2SnFI-jCdQcq3bt0m03gWgCtjRA; _csrf=Oq_o_Lo_dhhDXqZHQ95NhBp8Nvzntx1FUG-2ryAi6nA
Host: localhost:5000
Connection: close
User-Agent: Paw/3.1.5 (Macintosh; OS X/10.13.4) GCDHTTPRequest
```

Flask prints `{'_csrf': 'Oq_o_Lo_dhhDXqZHQ95NhBp8Nvzntx1FUG-2ryAi6nA'}` which means it is taking the second value, that seems to be more appropriate behavior and what Falcon is using.

**Comment by NikolaJankovic** [comment]
What's the consensus on this issue? I agree that it goes against best practice but it could still be helpful for some use cases. I could work on it this weekend but I'll defer to you guys on whether or not it should be adopted.

**Comment by Nateyo** [comment]
This is an interesting part of [RFC 6265 - 4.2.2](https://tools.ietf.org/html/rfc6265#section-4.2.2):
> Although cookies are serialized linearly in the Cookie header,
   servers SHOULD NOT rely upon the serialization order.  In particular,
   if the Cookie header contains two cookies with the same name (e.g.,
   that were set with different Path or Domain attributes), servers
   SHOULD NOT rely upon the order in which these cookies appear in the
   header.

However, it does not seem to mention which cookie should take precedence when two are set with the same name. The one with a more specific path? I think in the case given above there is no obvious choice, and therefore it is incorrect usage.

I think the answer is still that ONE has to take precedence. It seems falcon chooses based on whatever was added last, which based on the above spec could be interpreted as incorrect; although it does say SHOULD NOT. 😉 

Some solutions to the above answer:

- There are two csrf tokens, rename them to be more specific `csrf_form1` `csrf_form2`
- Concatenate the tokens somehow and encode them in Base64
    > To maximize compatibility with user agents, servers that wish to
       store arbitrary data in a cookie-value SHOULD encode that data, for
       example, using Base64 [RFC4648].
