### ISSUE TITLE
Consider changing context type to a bare class

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1120]
Consider changing from using a dict to a bare class and setting attributes on it, also removing the ability to use a custom class (since allowing for attribute-based access was the primary motivation for allowing the use of a custom context class in the first place).

I performed a few benchmarks under Python 2.7.13 and python 3.6.2 and discovered that using a bare class is actually faster in most cases. It was slightly slower (on the order of nanoseconds) for setting a value.

**Comment by kgriffs** [comment]
On second thought, we may retain the ability to use a custom class so that app users can ease migration by setting it back to a dict.

**Comment by vytas7** [comment]
@steven-upside have you had a chance to look into this issue?

I am thinking to hack something myself if this is still desired for 2.0.

And I would strongly advocate retaining the custom class ability since I know that some users (read: me :slightly_smiling_face: ) have already adopted this functionality. It would be a no-op them.

**Comment by vytas7** [comment]
Closing as the referenced PR has been merged.
