### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ezegusmargl** [falconry/falcon#1126]
Hi. Any Falcon example that I try on my server with 
Waitress responds me a 500 Internal Server Error always

This is my app.py

```
import falcon
 
class ThingsResource(object):
    def on_get(self, req, resp):
        """Handles GET requests"""
        resp.status = falcon.HTTP_200
        resp.body = 'Hello world!'
 
# falcon.API instances are callable WSGI apps
wsgi_app = api = falcon.API()
 
# Resources are represented by long-lived class instances
things = ThingsResource()
 
# things will handle all requests to the '/things' URL path
api.add_route('/things', things)

```

Im running on Windows Seven x64 & python 2.7.4 x64

![image](https://user-images.githubusercontent.com/14821271/31555934-48e8a382-b019-11e7-9afb-ee804959c362.png)

![image](https://user-images.githubusercontent.com/14821271/31556022-a682d792-b019-11e7-821e-e6b4fe898e9e.png)

Any Help?

**Comment by kchomski-reef** [comment]
@ezegusmargl you've passed module `app` to `waitress` instead of `wsgi_app`.
Instead of this:
`waitress-serve --port=8000 ezAPI:app`
you should run:
`waitress-serve --port=8000 ezAPI:app.wsgi_app`
Then you can access your endpoint at `http://whatever:8000/things`:
![falcon](https://user-images.githubusercontent.com/32264853/32853042-44c14080-ca3a-11e7-9251-ff2f8876a66f.png)
