### ISSUE TITLE
datetimes in params of simulate_<http> methods.

### ISSUE THREAD

**Issue by fyaretskiyso** [falconry/falcon#1161]
If you place a datetime into the params dictionary, it becomes distorted in the req.params. The result is 2017-12-11T18:50:45 00:00 where it should be 2017-12-11T18:50:45+00:00. The missing '+' doesn't allow correct parsing by the dateutil parsing.

**Comment by kgriffs** [comment]
Hi @fyaretskiyso, the ``+`` character is often used instead of ``%20`` to represent spaces in query string params, due to the historical conflation of form parameter encoding (``application/x-www-form-urlencoded``) and URI percent-encoding.  Therefore, Falcon, converts ``+`` to a space when decoding the query parameters.

RFC 3986 actually specifies ``+`` as a reserved character, and recommends percent-encoding any such characters when their literal value is desired (``%2B`` in the case of ``+``). 

In your case, that would mean passing ``2017-12-11T18:50:45%2B00:00`` instead of ``2017-12-11T18:50:45%2B00:00``.

**Comment by kgriffs** [comment]
[Please reopen if escaping doesn't work out and we'll explore some other options.]
