### ISSUE TITLE
Contribute optimizations to the python-mimeparse project

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1183]
Optimizations may include:

- [ ] Cython support (simply compiling and/or *.pyx modules)
- [ ] Algorithms
- [ ] Micro-optimizations

Also consider simply implementing our own media type parsing and removing this dependency, or creating our own standalone project under falconry/*

**Comment by foresmac** [comment]
Doesn't look like this project has had any updates since 2016, and it's not a complicated library. But how often does one run into `q` values in an `Accept` header? Does falcon even really need what this ostensibly does? Couldn't we just pick the first match from `Accept` that falcon is configured to support? Honestly, I've only encountered a few APIs that support more than one serialization format.

**Comment by vytas7** [comment]
Now that `python-mimeparse` has been moved to Falcrony, closing this issue in favour of https://github.com/falconry/python-mimeparse/issues/40.
