### ISSUE TITLE
Migrate MessagePackHandler, tests from msgpack-python to msgpack

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1199]

**Comment by vytas7** [comment]
APIs should be compatible for the time being, but ``msgpack`` 0.5.0+ notes that one should explicitly specify *use_bin_type* to avoid surprises in the future, since the default might be changed.

> Early versions of msgpack didn't distinguish string and binary types (like Python 1). The type for representing both string and binary types was named raw.

> For backward compatibility reasons, msgpack-python will still default all strings to byte strings, unless you specify the use_bin_type=True option in the packer. If you do so, it will use a non-standard type called bin to serialize byte arrays, and raw becomes to mean str. If you want to distinguish bin and raw in the unpacker, specify encoding='utf-8'.

> In future version, default value of ``use_bin_type`` will be changed to ``True``. To avoid this change will break your code, you must specify it explicitly even when you want to use old format.

IMHO the above sounds like a good default for practical use in serialization [1], so one could proactively specify it to be ``True``.

1. https://github.com/msgpack/msgpack-python

**Comment by kgriffs** [comment]
FWIW, ``falcon.media.MessagePackHandler`` passes ``use_bin_type=True``

**Comment by kgriffs** [comment]
Note: For Falcon 2.0, we just need to cleanup the tests to no longer use msgpack-python for py26/33, and adjust the docstring for ``MessagePackHandler``.

**Comment by vytas7** [comment]
Aha, sorry for the false alarm, sounds like that part is already covered. Then it might be just the package name change indeed.

**Comment by kgriffs** [comment]
I _think_ this work is done. Let me know if I missed something.
