### ISSUE TITLE
Add default file name in the StaticRoute 

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1224]
Consider adding the ability to specify a default filename for a static route. 

I'm not sure if it would be best to send the file or raise an `HTTPMovedPermanently` (or a `HTTPPermanentRedirect`). 
Probably for performance reasons the redirect would be best (but in this case maybe `default_filename` should become `default_location`)

**Comment by CaselIT** [comment]
Thinking back at my use case, serving a single page application html file, the two alternatives are not the same, since by using a redirect the original url would be lost, and with it the location on the spa.

**Comment by timc13** [comment]
There should be an overrideable default `index.html` that is served if the root path to the app is served.  This is how most static content hosting works.  No redirect logic necessary.

**Comment by CaselIT** [comment]
I'll try to implement it. 
I was thinking about leaving the default route optional though.

**Comment by kgriffs** [comment]
I think this could be a valuable feature to add to the framework, but before we proceed, I want to get crystal clear on our goals. I think we're actually conflating two different use cases:

**(A)** Serve a default file if the filename is not provided (ala the NGINX `index` directive)
**(B)** Serve a default file if a filename is given, but that file does not exist.

Re **(B)**, sites usually just respond with a 404 in that case.

Judging by #1224, it seems like you may actually be after **(A)**. If that's the case, you don't want to check whether or not the file exists, but rather examine the requested path. While less simple to implement vs. **(B)**, it _is_ common for sites to behave this way, and therefore satisfies the Principle of Least Suprise.

For **(A)**, the following situations would need to be taken into account in the impelementation, and would also of course need to be covered with tests (my apologies for the table formatting; markdown isn't always the best way to express this sort of thing):

| Variation | `req.path`        | `self._prefix`  | `self.options.strip_url_path_trailing_slash`     | `self._default_filename is not None`   | Response                                                                                                                                                                                                                                                                                            | Notes                                                                                                                                                                                                                                                                                                                          |
| --------- | ----------------- | --------------- | ------------------------------------------------ | -------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| 1         | `'/'`             | `'/'`           | *                                                | `True`                                 | Default file if it can be opened, otherwise 404.                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                |
| 2         | `'/'`             | `'/'`           | *                                                | `False`                                |  404                                                                                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                |
| 3         | `'/foo/bar'`      | `'/foo/bar/'`   | `True`                                           | `True`                                 | Default file if it can be opened, otherwise 404.                                                                                                                                                                                                                                                    | Falcon's default behavior is to normalize request paths so that paths  with and without trailing slashes are treated the same. Therefore,  `req.path` should probably be treated in this case as though it were  `'/foo/bar/'`, regardless of whether `env['PATH_INFO'][-1] == '/'`.                                           |
| 4         | `'/foo/bar'`      | `'/foo/bar/'`   | `False`                                          | `True`                                 | Default file if it can be opened, otherwise 404.                                                                                                                                                                                                                                                    | Although the developer has decided to disable the stripping of trailing slashes, one could argue that we should still just return the default filename in this case since it won't be obvious to the developer that there is this sort of relationship between `strip_url_path_trailing_slash` and `add_static_route()`.       |
| 5         | `'/foo/bar'`      | `'/foo/bar/'`   | *                                                | `False`                                | 404                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                |
| 6         | `'/foo/bar/'`     | `'/foo/bar/'`   | `False` (won't ever be `True`)                   | `True`                                 | Default file if it can be opened, otherwise 404.                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                |
| 7         | `'/foo/bar/'`     | `'/foo/bar/'`   | `False` (won't ever be `True`)                   | `False`                                | 404                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                |
| 8         | `'/foo/bar/baz'`  | `'/foo/bar/'`   | *                                                | *                                      | Behave as in the other variations, above, except that first it must be  determined whether the path beyond the prefix refers to a directory or a  file on disk. If a file, respond with that. Otherwise, respond with the specified default file in that directory if it can be opened, 404 if not. |                                                                                                                                                                                                                                                                                                                                |
| 9         | `'/foo/bar/baz/'` | `'/foo/bar/'`   | `False` (won't ever be `True`)                   | *                                      | Same as above.                                                                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                |

Let me know what you think and how this fits in with your original use case.

**Comment by CaselIT** [comment]
Thanks for the Feedback @kgriffs 

My intent was a bit of a mix of the two:
> Serve a default file it the path does not resolve to a file


The use case that i had in mind for this issue was a SPA, where regardless of the url that the user requests, the server always need to send the single html file with the application.

Maybe the name `default_filename` does not properly cover this use case. Maybe something like `fallback_filename` would be more appropriate?

**Comment by kgriffs** [comment]
@CaselIT Thanks for the clarification. In that case, I like the suggestion to rename the kwarg to `fallback_filename`. We can always implement **(A)** another time if/when the community requests it.

**Comment by CaselIT** [comment]
I've thought of an alternative that maybe can be a compromise:
keep the name `default_filename` but specify with a boolean flag ( called `default_filename_absolute` in the table below for lack of a better name) if it should be relative to the path selected or absolute. 
Something like:

| `default_filename` | `default_filename_absolute` | `prefix` | `directory` | `path` | file read |
| -- | -- | -- | -- | -- | -- |
| `foo.html` | `*` | `/static` | `/tmp/static` | `/static` or `/static/ | `/tmp/static/foo.html` |
| `foo.html` | `False` | `/static` | `/tmp/static` | `/static/bar` or `/static/bar/` | `/tmp/static/bar/foo.html` |
| `foo.html` | `True` | `/static` | `/tmp/static` | `/static/bar` or `/static/bar/` | `/tmp/static/foo.html` |

This alternative preclude the use of both method __(A)__ and `fallback_filename`

Let me know what you this. In the meantime I've changed the name to `fallback_filename`.

**Comment by snobu** [comment]
This isn't out on pip yet, am i right? Tried with --pre and i'm getting 1.4.1 from January. If you could push this commit as the new --pre that would be wonderful, thanks!

**Comment by CaselIT** [comment]
@snobu I second that!
