### ISSUE TITLE
Translate document to japanese

### ISSUE THREAD

**Issue by shimakaze-git** [falconry/falcon#1225]
Hi, I’m a Japanese Engineer in Tokyo.
I’m using Falcon at work. I would like to translate the falcon documentation into Japanese, so my coworkers and other developers can use this great framework!
How can I go about getting started?

**Comment by kgriffs** [comment]
Hi @shimakaze-git, I apologize for the delay in getting back to you. I think a lot of members of the community would appreciate a Japanese translation, and setting up the project docs for localization will set the stage for translating them into other languages as well.

That being said, this would be an ongoing project; before each release of the framework, I would need your help to go through the process of updating all the translations for the documents that changed since the last release. Since there is a fair amount of churn in the documentation between releases, it may be best to wait until a new release is imminent until working on the translation. I could notify you at that point. 

You would of course be free to pass the responsibility on at any time to another volunteer; the important thing is that the Japanese translations don't become outdated.

If you are agreeable, it looks like we'll need to follow the process outlined here:

http://www.sphinx-doc.org/en/master/intl.html

I believe I can [configure a sub-project](http://docs.readthedocs.io/en/latest/localization.html) on Read The Docs to set the language by passing `-D` to `sphinx-build`.

**Comment by vytas7** [comment]
Merging with #833
