### ISSUE TITLE
Wrong charset when uri is received

### ISSUE THREAD

**Issue by TihonV** [falconry/falcon#1227]
Steps to reproduce:

1. Create api-server with one registered sink method.
```
# app.py
import falcon

class ProxyToOldAPI(object):
    def __call__(self, req, resp, path):
        resp.content_type = 'application/json;charset=utf-8'
        resp.status = falcon.HTTP_200
        resp.data = ''.join([
            '{"uri":', path, '}'
        ]).encode()

def create_app():
    api = falcon.API()
    api.add_sink(ProxyToOldAPI(), r'^/old/(?P<path>.*)$\Z))
    return api
```

2. Run server:
`gunicorn app:get_app()`

3. Make request with curl:
`curl -H "Content-Type: application/json;charset=utf-8" http://localhost:8000/old/Киррилица`

![2018-03-06 21-57-46](https://user-images.githubusercontent.com/5057658/37055106-80f47c6a-2189-11e8-861d-a7eed69819cf.png)

```
$ python -V
Python 3.6.4
$ pip list | egrep falcon 
falcon (1.4.1)
falcon-cors (1.1.7)
```

**Comment by kgriffs** [comment]
Hi @TihonV, sorry for the delay in responding. curl unfortunately doesn't handle non-ASCII characters very well. So by the time the path reaches Falcon it is already garbled. You can percent-encode the URL to work around this, or use a tool like HTTPie instead of curl. I also tested making a request to your sample app via requests running in a python REPL and it round-tripped the characters in the path correctly.

**Comment by nZac** [comment]
Hi @TihonV, we haven't heard back from you so I am going to assume you have got it working on your side. If not, feel free to reopen this.
