### ISSUE TITLE
Transform + stream responses

### ISSUE THREAD

**Issue by subesokun** [falconry/falcon#1232]
Hi, I'd like to transform and forward an incoming stream as a response stream. My very naive approach transforms the incoming stream but sends it as bulk back to the client... 

The request stream contains line delimited JSON Arrays
```
["some", "data"]
["other", "data"]
... many more
```

and the response stream should look like the following
```
["some", "data", true]
["other", "data", false]
... many more
```

Any idea on how I can send immediately every transformed line back to the client?

```
    def on_post(self, req, resp):
        req_stream = codecs.getreader("utf-8")(req.stream)

        resp_read_fd, resp_write_fd = os.pipe()
        resp_write = io.open(resp_write_fd, "w")
        resp_read = io.open(resp_read_fd, "rb")

        resp.stream = resp_read
        resp.status = falcon.HTTP_200
        resp.content_type = falcon.MEDIA_TEXT

        for line in req_stream:
            data = json.loads(line) # Each line contains an JSON array e.g. ["some", "data"]
            data.append(True) # transform to ["some", "data", True]
            resp_write.write(json.dumps(data) + '\n')
            time.sleep(1)
```

Thanks a lot!

Python: 3.6.4
WSGI Server: gunicorn

**Comment by vytas7** [comment]
Interesting question @subesokun !

I am afraid, though, the short answer is it in general not possible to force clients to read any response before the whole request is streamed. HTTP standard does not say a client, for instance, a browser, must listen to response before transmitting the full request.

And even if they do, a typical use case for this is to detect ``4xx`` or ``5xx`` errors early instead of wastefully pushing massive request bodies for minutes or hours.

Another problem is how WSGI deals with this. But I believe you *should* be able to return a generator which renders response to request stream. Furthermore, you would not be able to guess the response size this way, so it must be streamed using chunked transfer encoding.

Which HTTP client would use this type of service?
Unless you are completely sure your client can cope with this scenario exactly as you wish, I would look into other protocols instead of HTTP for you use case. If it is browsers you are interested in, you could use Websocket, and so on.

**Comment by subesokun** [comment]
Hi @vytas7, thanks a lot for your quick reply! Actually we're in control of both the server and the client and we've a Node.JS based prototype running (for both server and client) and there it works as expected. As soon as the first byte gets streamed back from the server to the client the HTTP header gets send as well with an undefined `Content-Length` as we don't know the length yet. I guess I'd need to perform the transformation in a separate thread to avoid blocking the request... but sounds like this is a rare use case so I probably should keep my fingers away from it :p
