### ISSUE TITLE
support for HTTP 419 status code

### ISSUE THREAD

**Issue by mxmader** [falconry/falcon#1238]
While this code is not officially (to my knowledge) part of an RFC / standard, it seems to have colloquial use / adoption on many Internet-facing web services. 

Here's another framework who is considering this support (granted, the context is a bit different WRT falcon):
https://github.com/GetBlimp/django-rest-framework-jwt/issues/158

I'll post a basic PR to illustrate the request; no pressure to merge it as I am unsure what falcon's policy on RFCs/standards is (whether or not adherence thereto is a tenet/goal of this project).

**Comment by mxmader** [comment]
A bit more about my use case:

My team has built a REST API which uses the "Bearer Token" authorization model. I have various consumers, one of which is a client based on requests. That REST API will return various status codes depending on the semantics of the response to a given request which requires authentication and authorization:

HTTP 401 Unauthorized: when no token is given or an invalid/unknown token is given by the requestor
HTTP 403 Forbidden: when a valid, known token is given by the requestor (a client is thus identified/authenticated) but the requested resource requested falls outside their set of allowed resources (permission denied to the known client)
HTTP 419 Authentication Timeout: when an expired token is given by the requestor
The case of submitting an expired token is special, in that clients may choose to use the HTTP 419 status code value (instead of parsing and interpreting a potentially changing string in the response body of an HTTP 401 response) in order to more conveniently make a decision on what to do next.

**Comment by mxmader** [comment]
Note that the associated PR is posted for convenience and suggestion, not assertion. It's entirely reasonable for the maintainer to seek upstream standards body coverage before a change like this goes in. At a minimum, this issue will reflect the inquiry for historical record.

**Comment by nZac** [comment]
Werkzueg does not support it natively, but you can return any http code https://github.com/pallets/werkzeug/blob/e378a8f83d7549904abd7ae5b7ac53491a3c76cf/werkzeug/http.py#L141-L142

Bottle _implicitly_ supports it, however since httplib doesn't support it, it doesn't get mapped anywhere: https://github.com/bottlepy/bottle/blob/1de24157e74a6971d136550afe1b63eec5b0df2b/bottle.py#L4274-L4283

CherryPy uses the same: https://github.com/cherrypy/cherrypy/blob/98f2cfb110f9713f106bd1ac9bccac54d6bdd6a6/cherrypy/lib/httputil.py#L25

I couldn't find anything for zope/plone.

**Comment by mxmader** [comment]
closed my PR (#1239) in favor of #1242.

**Comment by jmvrbanac** [comment]
We do try to keep relatively close to the widely accepted standards. Since the standards bodies haven't made a determination about the future of code `419`, we would prefer to wait on adopting this change until there is a direction indicated by the bodies. We can reopen this issue at that time.

In the meantime, Falcon currently allows the use of custom statuses e.g `resp.status = '419 Authorization Timeout'` and custom error classes (via subclassing `HTTPError`). This should handle your use-case until the future of 419 becomes clearer.
