### ISSUE TITLE
Make using Cython with Falcon easier

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1281]
Ideas:

* Specify cython with setuptools extras
* Ship manylinux wheel

**Comment by kgriffs** [comment]
(Re manylinux we can port the build script from the 2.0 branch.)

**Comment by koobs** [comment]
While we're leveling up cython/packaging with regard to falcon, some additional notes, quoted from Cython documentation [1]

 * It is strongly recommended that you **distribute the generated .c files** as well as your Cython sources, so that users can install your module without needing to have Cython available.

 * It is also recommended that Cython compilation not be enabled by default in the version you distribute.  Even if the user has Cython installed ...

[1] http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules

**Comment by vytas7** [comment]
Discussion from https://github.com/falconry/falcon/pull/1753 (see also other comments therein)

@CaselIT said
> I think all of the supported manylinux images. https://github.com/RalfG/python-wheels-manylinux-build/tags
> Manylinux 2014 does support s390x: https://github.com/pypa/manylinux#manylinux2014
> 
> When creating wheels for sqlalchemy, I've read that is still suggested to use manylinux2010 (or manylinux1 if support for older linux is required). I'm using the 2010 in sqlalchemy, but it manages to automatically create also the manylinux1 version.
> Both are uploaded to pypi and pip chooses the appropriate one for the system

**Comment by vytas7** [comment]
Thanks for your feedback @koobs !
We'll think of shipping the generated `.c` files; that's an interesting idea.

When it comes to not enabling Cython by default, I'm admittedly not sure I'm following the reasoning, particularly if we follow the `.c` file advice.
Regardless, this issue is mostly about binary wheels, and that is where you obviously do want to compile whatever possible.

**Comment by CaselIT** [comment]
I can take a look at adapting the release workflow used in sqlalchemy for falcon, if the plan is to migrate to use github actions

**Comment by vytas7** [comment]
Re shipping `.c` files, I would be reluctant littering Git with them, and more importantly, having the burden of keeping them in sync with `.py` & `.pyx`.

Which means, if we pursue this, we'd probably have to
* Accommodate `setup.py` to be able to use these `.c` files, if present
* Generate them in GH release Actions (similarly to building wheels) when generating `sdist`, before uploading `sdist` to PyPy.

**Comment by CaselIT** [comment]
So the plan could be:
- The action runs when a release is created

### For wheels:
- generate the wheel compiling the parts to compile
- install the created wheel. On linux this would use the manylinux docker image to generate correct linux images
- check that the compiled parts are properly setup.
   - [ ] if there is currently a way for falcon to detect this. Maybe a flag somewhere may be useful. Something like `falcon.utils.with_cython: bool`?
- run the test suite on the installed wheel.
   - [ ] Is there a way of running the test against the installed version, ignoring the source file (I guess we could do a `rm -rf falcon` before testing :) )
- upload the wheel(s) to the release
- upload the wheel(s) to pypi (this maybe starts for the first release by targeting the test pypi)

### For sdist
- (optional) generate c files with cython
- create the sdist
- install the sdist with cython
- run test on the installed version, (see above for the question regarding running test)
- install the sdist without cython
- run test on the installed version, (see above for the question regarding running test)
- upload the sdist to the release
- upload the sdist to pypi (this maybe starts for the first release by targeting the test pypi)


Regarding wheels, to start it may be linux/win/macos x64 (not sure regarding x32 windows). Following maybe the other architecture, like arm and s390x

Does this work? I've just two open question that I may need support with

**Comment by vytas7** [comment]
Summarizing some thoughts from Gitter as well.

### Wheels
* It might be possible to run `tox` with `skipsdist` set to `True`, and somehow injecting the newly produced wheel file into `deps`.
* Source files are not an issue with `tox` / `pytest`; I have solved this by simply removing `tests/__init__.py`: https://github.com/falconry/falcon/issues/1400
* No 32 bit systems are priority; in fact, it might be even good to skip them on purpose, because we are not testing them much. In fact, the cythonized stream reader is not used on 32 bit systems by design, because it heavily relies on standard machine size types, which would effectively cripple accepting multpart forms larger than 2 GiB.
* It would be awesome to support all 64 bit Linux architectures laid out in [`manylinux2014` (PEP 599)](https://www.python.org/dev/peps/pep-0599/), plus Mac and Windows (not a priority).

### sdist
* C files are not a high prio; we might want to do a proof of concept without complicating matter too much.
* Testing `sdist` is probably not a super high prio, because that's exactly what normal `tox` runs are supposed to do.

**Comment by CaselIT** [comment]
Regarding wheels macos and windows, they are super easy to do, just run `pip wheel` and you are basically done :).

Regarding signing for the sdist, I don't think there is a need to sign it. Is the current source distribution signed?

**Comment by kgriffs** [comment]
Re signing, I currently use twine to do that, although it is more of a nice-to-have, since most people never bother to check the sig.

**Comment by kgriffs** [comment]
Also, as we look into more fully automating the build/release process don't forget that we must check that that README will render on PyPI before publishing a new version. This is currently done with `twine check` (see also: `tools/build.sh`)

**Comment by koobs** [comment]
> 
> 
> Re shipping `.c` files, I would be reluctant to litter the source tree with them, and more importantly, to have the burden of keeping them in sync with `.py` & `.pyx`.
> 
> Which means, if we pursue this, we'd probably have to:
> 
>     * Accommodate `setup.py` (or other build tool in case we switch as part of PEP 517 migration) to be able to use these `.c` files, if present.
> 
>     * Generate them in GH release Actions (similarly to building wheels) when generating `sdist`, before uploading `sdist` to PyPy.

Note that the upstream (Cython) recommendation, as it seems your comment/interpretation above eludes to, is not for the source repository to contain the generated C files, but for those to be provided in/by the sdist (as they are, the 'source' distribution)

**Comment by CaselIT** [comment]
> Also, as we look into more fully automating the build/release process don't forget that we must check that that README will render on PyPI before publishing a new version. This is currently done with `twine check` (see also: `tools/build.sh`)

Yes, the current master has an error in the readme: https://github.com/falconry/falcon/pull/1754/files#diff-88b99bb28683bd5b7e3a204826ead112

I think we should probably add a test for it in the normal ci that @vytas7 is working on
