### ISSUE TITLE
feat: Add a way for Middleware process_request() to indicate whether routing should proceed or the response should just be rendered immediately

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1296]
We can either set an attribute on `resp`, or simply support returning a truthy value to indicate whether or not the routing should be short-circuited. Other ideas?

Should we also do this for process_resource()?

**Comment by fgimian** [comment]
Yes please.  We would like this too so that we can have middleware that does caching and doesn't proceed to the actual resource if the response is already cached.

**Comment by mattgiles** [comment]
Why wouldn't it be preferred to raise an `HTTPError` or `HTTPStatus`? Raising an exception is a really nice pattern for short-circuiting handlers and middleware.

**Comment by vytas7** [comment]
@mattgiles raising an exception is very handy for short-circuiting request processing indeed.
However, there are both philosophic and technical reasons why it is not always the preferred way.

First, in Python (and many other languages) raising an exception signals that something unusual or unexpected has happened as opposed to the ordinary case. If, for instance, CORS middleware is rendering a response to ``OPTIONS``, it is completely normal behaviour, not any exception in the program logic. Furthermore, these ``HTTPStatus`` exceptions would be handled in the API's error handlers registered with ``add_error_handler`` which might confuse the user if he or she is already handling any ``HTTPStatus`` exceptions this way.

Second, short-circuiting the response has a slightly different meaning in the request processing chain. The response object is not created solely by the last middleware short-circuiting it, but potentially modified by earlier middlewares, hooks etc in the chain, whereas raising an ``HTTPStatus`` requires you to craft it from the scratch. What is more, ``HTTPStatus`` does not provide the same interface as ``Response`` does. For instance, suppose you have some imaginary cache middleware returning a cached version of the response which is streamed from an internal caching server. Right now you can only provide *body*, *headers* and *status*, but not an equivalent of ``resp.stream``. The same goes for many utility properties, although you can set many of the through headers, but you lose the convenient interface. Sure, maybe ``HTTPStatus`` could be redesigned to wrap a ``Response`` somehow, but it is IMHO valid to question the pattern itself.

**Comment by vytas7** [comment]
A comment on the issue itself. It would feel very natural supporting a truthy value to indicate whether or not the routing should be short-circuited. However, we would need to find an alternate way (such as an attribute on ``resp``) if we further pursue https://github.com/falconry/falcon/issues/1047 .

**Comment by mattgiles** [comment]
@vytas7 totally. That's super reasonable, and makes sense on several counts. I was curious, and appreciate the thoughtful response.

To elaborate on my curiosity. I don't know if I agree that, in Python, exceptions are idiomatic only in cases where something has gone wrong. Python is also *unlike* many languages insofar as its exception handling can be used proactively to manage the flow of control.

Indeed, part of what I find so elegant about falcon is the main loop in `API.__call__`, a prominent feature of which is the explicit handling of both `HTTPError` and `HTTPStatus` as exception classes. The original idea might have been to lean in to the semantic similarity between HTTP error codes and program exceptions -- but that choice being made, it's no surprise that the broader identity of HTTP status codes and exceptions was embraced.

It's an intuitive and simple pattern: falcon provides a well-structured flow for requests and responses to traverse, but if at any point in that flow I determine exactly what the content of the response should be, I can jump out. Because this seems to be exactly the situation this issue is considering, I guess I was curious why it would be pursued by other means.

As you point out, these exception classes do not do what you need them to in order to address this issue in its particulars. But, as you also point out, they could -- and in a way which seems harmonious with #1047.

**Comment by kgriffs** [comment]
I'll go ahead and take a stab at this.
