### ISSUE TITLE
list all routes?

### ISSUE THREAD

**Issue by timc13** [falconry/falcon#1315]
Is there a way to list all routes from the default compiled router?

**Comment by cnds** [comment]
``` python
routes = []
routes.append(('/route1', DoSomething))
routes.append(('/route2', SomethingElse))

class Application(falcon.App):
    def __init__(self, routes, config):
        super(Application,self).__init()
        for route, handle in routes:
            self.add_route(route, handle(config))

app = Application(routes, config)

```

now you can get all routes from routes list

**Comment by vytas7** [comment]
Hi @timc13 ,
We are maintaining the semi-official `falcon-print-routes` which is accessible in the environment you install Falcon in.

I would need to check if that tool only uses officially documented public compiled router APIs, but looking at the source code it doesn't seem to look like too horrible sorcery either. And as said above, we are trying to maintain that tool, I think, it even has a couple of unit tests verifying it keeps working with the current compiled router.

You can find the tool here: https://github.com/falconry/falcon/blob/master/falcon/cmd/print_routes.py

I'm closing this issue hoping the tool source could serve as inspiration, but do not hesitate to reopen if you find this too hacky or otherwise unacceptable.
