### ISSUE TITLE
Best way to cite Falcon framework in a paper

### ISSUE THREAD

**Issue by tboch** [falconry/falcon#1380]
What is the preferred way to cite the usage of Falcon framework in a scientific paper? A link to the home page? Or is there a reference paper?

**Comment by vytas7** [comment]
Hello @tboch !
I believe this is still a bit of a gray zone, and it varies greatly between different journals / scientific societies.

If you are publishing in APA managed- or related journals, you might want to follow the APA Style [1].
Furthermore, MIT has some general advice on citing software [2]. I don't think we have a DOI for a publication presenting Falcon project though, at least not that I know of.

Looking into our friends/competitors, another popular open source web framework Django has a general answer in line with the above [3].
For Falcon, I guess we could craft something in that vein as well:
```
Falcon (Version 1.4.1) [Computer Software]. (2018). Retrieved from https://falconframework.org.
```

Needless to say, take my advice with a grain of salt. I actually do hold a PhD but that was in Applied Physics, so the citing standards might differ somewhat there, and it's been a while since I moved away from research.

I am closing the issue hoping this could serve as a starting point, but do not hesitate to reopen, or open a new question should you need further help. And please let us know if you get any publications out citing Falcon, that sounds really cool! :cool: 


Kindly
Vytas

1. https://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html
2. https://libguides.mit.edu/c.php?g=551454&p=3900280
3. https://docs.djangoproject.com/en/2.1/faq/general/#how-do-i-cite-django
