### ISSUE TITLE
almost a year since last version

### ISSUE THREAD

**Issue by bpmason1** [falconry/falcon#1390]
The lastest version of falcon, version 1.4.1, was released January of 2018.  That's almost a year ago.  Is there any intention of creating a new release in the foreseeable future?

**Comment by kgriffs** [comment]
Hi @bpmason1, thanks for reaching out!

I apologize for the slow velocity this past year on the project. There were some things I had to take care of that temporarily reduced the amount of bandwidth I could devote to Falcon. 

The good news is that we are currently driving hard toward a 2.0 release. Our velocity has increased a lot lately thanks to a couple of factors. First, I brought two additional community members on to the core maintainers team (@vytas7 and @nZac), and they have been helping out a lot in a number of ways. Second, we have received donations from several generous patrons, allowing us to spend more of our personal time on the project. 

Over the past few weeks, we've merged a bunch of PRs in the backlog, and we should be caught up there very soon. Otherwise, there are a handful of odds and ends to finish up for 2.0, but January is looking very likely at this point. We will push out some of the work currently scheduled for 2.0, if necessary, to ensure a timely release.
