### ISSUE TITLE
Improve falcon-print-routes tool

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1435]
`falcon-print-routes` is a simple (albeit somewhat spartan) tool that may come handy to list API routes.
We could polish it, and expose more widely:
* Advertise it in the documentation (currently it is only mentioned in the `1.1.0` changelog)
* Make it aware of route suffixes, a new feature in 2.0
* Expose interface to be able to list routes programmatically (suggested by @CaselIT )
* Make it clear that the tool only works with the standard `CompiledRouter` (suggested by @CaselIT )
* Anything else? (suggestions welcome!)

**Comment by Nateyo** [comment]
I'll pick this one up!

**Comment by vytas7** [comment]
Cool, I didn't expect anyone to pick this so soon 👍 
Just a note: you may want to wait for this to land, or start off my branch -- it fixes a couple of bugs in this tool: https://github.com/falconry/falcon/pull/1399

**Comment by Nateyo** [comment]
Sure I can wait, I know we are deep in 2.0 beta territory as well. I have fond memories of when `flask routes` came out, so this is a nice thing for me to work on while I'm still learning a lot about how falcon works under the hood. 😄

**Comment by vytas7** [comment]
Well, as said, you don't really need to wait -- you can always just fork off my branch :slightly_smiling_face:

**Comment by vytas7** [comment]
Hi again @Nateyo !
Just wanted to check if you were still working on this tool, or had any code to share that some else could pick up?

**Comment by CaselIT** [comment]
@vytas7 I think another point to add is a check that the router is the default compiled router, since it will only work with that.

**Comment by CaselIT** [comment]
Also maybe moving the actual code that lists the routes in another module, like in `falcon.utils.explore_routes` or `falcon.routing.explore_routes` and make the script import it, would be easier to reuse programmatically.

**Comment by vytas7** [comment]
Thanks for these suggestions @CaselIT!
I updated the issue description.

**Comment by CaselIT** [comment]
Other random thought:

Add a `debug` keyword to the `App` (or to `App.add_route`) so that a log is printed every time a route is added to the application. This could be useful when first debugging the application to have an immediate feedback what routes are there and what causes a problem.

Regarding a kw in `App` vs one in `App.add_route` maybe one in `App` could be nicer since there could be similar logs for every "setup" call to the application. By setup I mean constructor log (middleware), calls to `add_route`, `add_static_route`, etc, basically everything that does not involve the normal handling of a request.

Maybe I can open another issue regarding this?

**Comment by vytas7** [comment]
That would be more fitting a separate issue IMHO, yeah. :arrow_upper_left:

**Comment by CaselIT** [comment]
I'm working on this in #1661
