### ISSUE TITLE
Attempt ordering exception handlers by exception class inheritance

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1514]
At the time of writing, exception handlers are matched in LIFO order, i.e. when searching for an error handler to match a raised exception, and more than one handler matches the exception type, the framework will choose the one that was most recently registered.

In case one has many error handlers for classes potentially inheriting from each other, this may become very error-prone and confusing in case a wrong handler swallows the exception.

Investigate if it is possible to order exceptions statically as they are being added (not at the time of catching).

Prior art: Flask/Werkzeug claim to handle this; investigate how it is done there.

**Comment by csojinb** [comment]
Since this is relevant to the other work I did with error-handling, I can dig into werkzeug and try to figure out what's going on there. Don't promise to finish said research though 😅

**Comment by csojinb** [comment]
[Here](https://github.com/pallets/flask/blob/1dda032b00cb4f7a783e018a7c370ee88f15e797/flask/app.py#L1678-L1682) are the relevant lines in Flask for using the most specific handler available. They have some additional levels of categorization for blueprints, or storing handlers by code instead of exception class, which don't seem relevant for Falcon.

So, basically, the error handlers are stored in a dict of `{<exception class>: <handler callable>}`. Then they iterate through `<raised exception>.__mro__` (which produces a tuple of the class hierarchy from least to most general) until a match is found in the error handler dict.

If y'all decide to do this, it seems like it should be pretty straightforward.

**Comment by csojinb** [comment]
@vytas7 I might be misunderstanding the issue here... what is the problem with having handlers associated with more than one exception? Can't you just store that as `{Exception1: handle_exceptions_1_and_2, Exception2: handle_exceptions_1_and_2}`?

**Comment by vytas7** [comment]
@csojinb No, there is no problem per se, that is what my suggestion #2 is basically aiming at.
You could store expand that to handlers in a way you depict, however, if possible, for performance reasons it would be good to keep exceptions grouped in case they sort equal on the inheritance scale.

**Comment by kgriffs** [comment]
Where did we end up on this issue? Is https://github.com/falconry/falcon/pull/1527 still waiting on this?

**Comment by vytas7** [comment]
@kgriffs this is, strictly speaking, not blocking #1527 .
But it would make the implementation more straightforward and consistent, but not having to care the default bare handler is invoked last.

**Comment by kgriffs** [comment]
OK, I'd love to have this smarter ordering implemented for 3.0 if we can swing it, otherwise push to 3.1.

**Comment by kgriffs** [comment]
Any volunteers? :)

**Comment by kgriffs** [comment]
P.S. When this is implemented, don't forget to update the note under the `add_error_handler()` docstring.

**Comment by vytas7** [comment]
I think Falcon users who (read: me :slightly_smiling_face: but I think @jmvrbanac also uses this pattern and has even advised users to do so) add a custom exception handler for `Exception` may also be re-raising `HTTPError` & `HTTPStatus` which are then caught in a special clause in `API._handle_exception`.

Not sure if we need to do much about this now though. The problematic should be gone once we introduce exception ordering.

**Comment by csojinb** [comment]
Hi, I put up a draft PR with an implementation for this. I was hoping to get some input on the approach before adding tests, etc.

I went with the simpler implementation because I didn't totally understand @vytas7's first suggestion for managing shared error handlers. Should I do a benchmark comparison or something for this implementation?

**Comment by vytas7** [comment]
Scratch those suggestions. Your proposed approach is way more scalable in the general case I think :+1: (it is only adding complexity traversing the MRO, but the class lookup itself is `dict`-based (O(1)-ish)).

**Comment by vytas7** [comment]
Resolved in https://github.com/falconry/falcon/pull/1603
Thanks @csojinb ! :tada:
