### ISSUE TITLE
missing a params in quickstart's JSONTranslator

### ISSUE THREAD

**Issue by xiaodi007** [falconry/falcon#1572]
def process_response(self, req, resp, resource, params):
        if not hasattr(resp.context, 'result'):
            return

**Comment by drunckoder** [comment]
I think he means middleware receives an empty dict (`<class 'dict'>: {}`) as `params` argument. I got the same problem with hooks. You can use `req.params` to get what you're looking for.

**Comment by xiaodi007** [comment]
tks, I will check out. I just thought maybe in quickstart add the params will be nice.

**Comment by fojetin** [comment]
The problem has already been resolved in [lattest docs version](https://github.com/falconry/falcon/blob/master/docs/user/quickstart.rst)
But stable docs version keep linked to [old docs release](https://github.com/falconry/falcon/blob/2556abce9afd9e0ea55d6aada09c64c311ca688e/docs/user/quickstart.rst)

@kgriffs i think you can close this issue, because problem will be automatically solved with the next release.

**Comment by kgriffs** [comment]
The names here are admittedly a bit confusing; it sounds like we may need to clarify the docs for the `params` argument passed to `process_resource()` and hooks to make it clear that they only contain values from the URI path, not the query string, and point the reader to `Request.params`. 

In the future, we should probably either rename the `params` argument to make it more clear how it differs from `Request.params` and/or implement query string support for the URI templates.
