### ISSUE TITLE
Media handlers do not get a chance to deserialize zero-length payload

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1589]
At the time of writing, `Request.media` property implementation starts this way:
```python
if self._media is not None or self.bounded_stream.is_exhausted:
    return self._media
```

If media in question is serialized to an empty (byte)string, i.e. the request `Content-Length` is zero, the `bounded_stream` is automatically considered exhausted. Hence `Request.media` automatically reduces to `None` without even resolving media handlers for the submitted content type.

While this is the correct behaviour for certain types of media, such as YAML, and for many other media types such as JSON, Msgpack, most audio/video/picture types etc it looks like an acceptable (albeit debatable since deserialization of empty input for these is undefined or defined to be malformed -- see also the discussion in https://github.com/falconry/falcon/issues/1216 ) workaround, there might be cases where an empty string could be expected to be deserialized to another value, such as in the `application/x-www-form-urlencoded` case:
```python
>>> import urllib.parse
>>> urllib.parse.parse_qs(b'')
{}
```

**Comment by kgriffs** [comment]
I agree that now would be a good time to address this long-standing issue while we can make some breaking changes for 3.0.

Based on my understanding of the discussion so far, this is what I propose in terms of requirements:

- [ ] Provide a more explicit way for the call chain and the app to distinguish between an empty body and a failure by a handler to parse the body. See also the next requirement.
- [ ] Provide a way for the app to override behavior when a parse error is encountered vs. just always returning with HTTPBadRequest (I like [this suggestion](https://github.com/falconry/falcon/issues/1216#issuecomment-448619858)).
- [ ] Allow different media handlers to treat an empty body in whatever way makes the most sense for the media type in question (and point this out in the docs for media handler implementers and in the implemented media handler docstrings). I don't think we need to have them raise an EmptyBodyError as suggested elsewhere. For example, `URLEncodedFormHandler` could return {} in that case, while `JSONHandler` could opt to return `None`.
- [ ] The `media` property should distinguish between the body having already been consumed vs. an empty body, and in the former case return whatever was parsed previously (if anything was parsed previously; otherwise if something else consumed the body before we had a chance at it, fall back to same behavior as an empty body?). This will require initializing `self._media` to some kind of special value rather than `None`.

**Comment by kgriffs** [comment]
FWIW the ASGI PR (https://github.com/falconry/falcon/pull/1573) implements these items with the exception of raising specialized error types. That can be done in a follow-up PR along with updating the WSGI side to suit.

**Comment by onecrayon** [comment]
The 3.0.0a1 release currently throws an HTTPBadRequest when using the default JSON handler on an empty body claiming the JSON is invalid. This surprised me, as I would have expected `req.get_media()` to return None or an empty object `{}` when there's legitimately nothing in the stream. Is this behavior intentional? It makes it difficult to discern the difference between an empty response, and a response that's legitimately malformed JSON since even if the endpoint uses try/except it just knows "JSON serialization failed for some reason".

**Comment by CaselIT** [comment]
Technically the current behavior is correct, since an parsing an empty string raised an error.
But I agree that maybe we could raise a subclass of `HTTPBadRequest` (maybe `HTTPEmptyRequest`) so that it's potentially easier to catch that case?

**Comment by onecrayon** [comment]
That would be very helpful for my use-case. I ran across this thanks to a decorator that wraps endpoints in order to apply FastAPI-style automatic documentation generation (which was checking for media on everything, but has no way to distinguish between a legitimate JSON parse failure, or a parse failure due to lack of content--which might actually be an expected thing to happen, e.g. on GET requests).

**Comment by CaselIT** [comment]
Coping from gitter:

An alternative, since we now have both a property and a method, we could add an argument to the `get_media` method to specify what to return when empty? `Request.get_media(when_empty=_default)` where `_default` is an private singleton object that maintains the current behaviour, that depends on the parser. Example json would raise by default, while yaml would return `None`.
This would also give another reason to introduce the `get_media()` method and in the future maybe deprecate `media`

**Comment by vytas7** [comment]
An important note on the ASGI side, before I forget again: in ASGI, in case it is a streamed request, it is hard to distinguish empty payload without actually trying to consume it, so we would probably need assistance from media handlers for a bullet-proof solution? :thinking:

**Comment by CaselIT** [comment]
Should we try to wrap up a reasonable proposal? My take

- Make the media try to parse an empty body. If it does not error, great, use that value.
- If it errors, check if the stream was empty. Use the content_length for wsgi. Not sure if it is possible in the async part, but it should still be possible to know if at least something was read after the fact.
- If it was empty check the `when_empty` parameter of `Request.get_media` and return it if it was provided.
- Raise an exception if `when_empty` was not provided. (It may still be worth raising a bad request subclass)

**Comment by CaselIT** [comment]
NOTE: The current behavior on wsgi is to return `None` in case of an empty body and to raise an exception of asgi :\

**Comment by vytas7** [comment]
> NOTE: The current behavior on wsgi is to return None in case of an empty body and to raise an exception of asgi :\

This is known; @kgriffs has stated it above:
> FWIW the ASGI PR (#1573) implements these items with the exception of raising specialized error types. That can be done in a follow-up PR along with updating the WSGI side to suit.

**Comment by vytas7** [comment]
@CaselIT great that you started the ball rolling with the PR, that looks good for the most of it.

I have some misgivings about the API for providing the fallback value though:
* For users of Falcon 2.0 that desire to get `None` in case of a missing body, needing to change every reference of `req.media` to `req.get_media(None)` is an almost equally breaking change as needing to surround it with `try... except`.
* For certain types of handlers, e.g., [`MultipartFormHandler`](https://falcon.readthedocs.io/en/latest/api/media.html#falcon.media.MultipartFormHandler) where iteration over parts is expected, supporting an empty body does not really make sense in the same way as JSON. Or maybe one could provide an empty iterable as fallback :thinking: 

Regardless of the fallback design, could it be worth supporting (optional?) reraising the error as a specialized exception instead? For instance, `HTTPMissingBody` (subclassing `HTTPBadRequest`, similar to `HTTPMissingParam`).

In order to ease porting for Falcon 2.0 users, could we simply add an option to [`JSONHandler`](https://falcon.readthedocs.io/en/latest/api/media.html#falcon.media.JSONHandler)?
