### ISSUE TITLE
Automatically generate homedoc

### ISSUE THREAD

**Issue by queertypes** [falconry/falcon#160]
It would be pretty awesome if based on routes registered for a Falcon application, Falcon was able to automatically generate a home doc.

More or less like:

``` python
api = falcon.API()
...
api.add_route('/v1/health', HealthController())
api.add_route('/v1/obj', ObjectController())
api.add_route('/v1/obj/{obj_id}', ObjectResource())
api.homedoc  # generates home doc as a Python dict
api.homedoc_route('/v1')  # outputs homedoc when user visits /v1
```

Depends on issue #35

**Comment by kgriffs** [comment]
If we do this, we should provide general affordances for generating a variety of API specs. I personally have mixed feelings about letting the code drive the spec, since that means the contract is fluid and prone to implementation errors, but this is something lots of people like to do, so should we support it anyway?

P.S. - I'm open to the idea of supporting the [home document proposal][1] out of the box, since it is IMO more in keeping with the spirit of REST than some of the alternatives. But it may be better to just afford this sort of thing and have add-ons in different projects for JSON Home, Swagger, etc.

[1]: https://tools.ietf.org/html/draft-nottingham-json-home-03

**Comment by nZac** [comment]
The home doc RFC is stagnant since 2017, so I don't think we will take it further.
