### ISSUE TITLE
 Cannot get the posted parameters from a application/json request.

### ISSUE THREAD

**Issue by raisoon** [falconry/falcon#1619]
Hey guys,
    I have set app.req_options.auto_parse_form_urlencoded to True,but when i run a http-post requests, i can only get a empty string with req.params.
   How could i resolve this problem？

（1）requests code:
import requests
headers = {'CONTENT-TYPE': 'application/json'}
r = requests.post('http://127.0.0.1:6280/uback', json={'k1':'v1'}, headers=headers)

（2）falcon code:
    app = falcon.API()
    app.req_options.auto_parse_form_urlencoded = True
    ucall = UCall()
    app.add_route('/uback',ucall)

**Comment by vytas7** [comment]
Hi @raisoon !
Given the provided snippets, I could guess that the issue lies in you actually sending JSON (`application/json`) request media to your application, not URL-encoded (`application/x-www-form-urlencoded`) request payload.

Using an application similar to your snippets:
```python
import falcon


class UCall:
    def on_post(self, req, resp):
        resp.media = {
            'params': req.params,
            'media': req.media,
        }


app = falcon.API()
app.req_options.auto_parse_form_urlencoded = True
ucall = UCall()
app.add_route('/uback', ucall)
```
...I can now test both JSON, and URL-encoded requests, respectively:
```python
>>> import requests
>>> # JSON payload
... requests.post('http://127.0.0.1:8000/uback', json={'k1':'v1'}).json()
{'media': {'k1': 'v1'}, 'params': {}}
>>> # URL-encoded payload
... requests.post('http://127.0.0.1:8000/uback', params={'k1':'v1'}).json()
{'media': None, 'params': {'k1': 'v1'}}
```

I am thus closing this issue hoping the above sheds some light on the topic, but do not hesitate to reopen if you have any further questions on Falcon request media handling.
You are also welcome to join us and ask for help on our [`falconry/user` Gitter channel](https://falconframework.org/#sectionCommunity)!

P.S. Note that the development version of Falcon also supports accessing [URL-encoded payload as `req.media`](https://falcon.readthedocs.io/en/latest/user/faq.html#how-can-i-access-posted-form-params). In the Falcon 3.0 alpha release, we will go on to install this media handler by default, and deprecate `auto_parse_form_urlencoded`.

**Comment by raisoon** [comment]
Sorry, i mean that i use req.params to get parameters from request, but i can only get a empty string.

**Comment by raisoon** [comment]
import falcon


class UCall:
    def on_post(self, req, resp):
        print('params:' + str(req.params))

--------------------------------
the print result is : params:{}

**Comment by vytas7** [comment]
Hi again @raisoon ,
have you had a chance to review my explanation in the comment above?

Enabling [`RequestOptions.auto_parse_form_urlencoded`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.auto_parse_form_urlencoded) only parses, as the name suggests, URL-encoded media of type `application/x-www-form-urlencoded `, not JSON:
> Set to `True` in order to automatically consume the request stream and merge the results into the request’s query string params when the request’s content type is `application/x-www-form-urlencoded` (default `False`).

In order to parse JSON payload, the easiest way is to use [`req.media`](https://falcon.readthedocs.io/en/stable/api/media.html).

**Comment by raisoon** [comment]
Hi @vytas7 ,
Thanks for your explanation! I have tested it successfully on my machine. But i meet another problem now: 
When i use req.media to get the posted parameters that come from someone else's http request, an exception happens:  "Invalid JSON,Could not parse JSON body - Expecting property name enclosed in double quotes: line 1 column 2 (char 1)" .Because i am able to reach them, what can i do to know what they posted to me?
Thanks!

**Comment by vytas7** [comment]
Hi again @raisoon !
Could you provide an example how your request looks like?
If the request `Content-Type` is `application/json`, then it should be valid JSON payload.

**Comment by vytas7** [comment]
Hi again @raisoon !
Closing the issue hoping you've solved this by now.

We'll try to add illustrations in our docs/FAQ on how to send JSON and URL-encoded requests to an application: https://github.com/falconry/falcon/issues/1636
