### ISSUE TITLE
How to send and receive images with Falcon Framework?

### ISSUE THREAD

**Issue by Mice948** [falconry/falcon#1637]
Hello
I am trying to send and receive images with requests library but I can't seem to succeed.
What Is the easiest way to send and receive an image?.
This is How I tried:
```
import requests
import base64
with open("test.png", "rb") as image_file:
     encoded_image = base64.b64encode(image_file.read())
r = requests.post("http://localhost:8000/image", data={'image_data':encoded_image}, headers={'content-type': 'image/png'})
```

and the server
```
json_data = json.loads(req.bounded_stream.read().decode('utf8'))
base64encoded_image = json_data['image_data']

with open('pic.png', "wb") as fh:
     fh.write(base64encoded_image)
resp.status = falcon.HTTP_200
```
How ever I am getting a Json error I'm not sure why, I cannot send JSON data because encoded_image is in bytes

**Comment by vytas7** [comment]
Hello @Mice948.
You can just send it as the request data, something along the lines of the [Streaming Uploads](https://2.python-requests.org//en/master/user/advanced/#streaming-uploads) recipe from the `requests` docs.

You can consume it on the application side as demonstrated in [our "Look" tutorial](https://falcon.readthedocs.io/en/stable/user/tutorial.html#request-and-response-objects), see the `on_post` handler.

In contrast to that example, depending on the WSGI server you use, you may want to use the [`req.bounded_stream` instead of `req.stream`](https://falcon.readthedocs.io/en/stable/user/faq.html#why-does-req-stream-read-hang-for-certain-requests).

Hope this helps. Closing this issue.
