### ISSUE TITLE
There is falcon.after, but is there any way to do middleware after?

### ISSUE THREAD

**Issue by FerusAndBeyond** [falconry/falcon#1707]
I would like to save each request but at the same time I don't want to insert to a database at each request before the response is returned to the user, now it would be perfect to do so directly after the response have been sent to the client and `falcon.after` seem to do the trick but adding it to every request is a bit annoying. Is there any middleware type functionality that can be performed after the request has been handled?

**Comment by CaselIT** [comment]
I think you can use the `process_response` if the middleware.
https://falcon.readthedocs.io/en/stable/api/middleware.html

**Comment by FerusAndBeyond** [comment]
@CaselIT Is that after the response has been sent to the client?

**Comment by CaselIT** [comment]
That is before. I think that the `process_response ` happens after the `falcon.after` callback.
I don't think it's possible to execute any action after the message has been sent to the client in wsgi, since the interaction terminates once the message has been returned to the wsgi server.

**Comment by vytas7** [comment]
@FerusAndBeyond ,
as @CaselIT also explains above, `process_response` actually executes after `falcon.after` since a `falcon.after` hook just decorates the responder method, and `process_response` is invoked [after the request has been processed by the routed responder](https://falcon.readthedocs.io/en/stable/api/middleware.html):
```
mob1.process_request
    mob2.process_request
        mob3.process_request
            mob1.process_resource
                mob2.process_resource
                    mob3.process_resource
            <route to resource responder method>
        mob3.process_response
    mob2.process_response
mob1.process_response
```

Are you streaming your response by setting [`resp.stream`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.stream) to an iterable or a file-like method?
If not, the above should be more than sufficient.

**Comment by FerusAndBeyond** [comment]
@CaselIT @vytas7 Okay, thanks for the help, will experiment and see what works.
