### ISSUE TITLE
Suggestion : Request body shall be available throughout the lifecycle of a request

### ISSUE THREAD

**Issue by humblewolf** [falconry/falcon#1738]
I am new to falcon and I may be missing something.

If in a responder I read body from request object, it seems I cannot read it again, (there is no seek(0)). 

This is troublesome If i want to log the entire request(body included) in case of some exception after reading body via global exception handler.

**Comment by vytas7** [comment]
Hi @humblewolf !
Falcon does not buffer or spool the request body by design.

In order to provide `seek()`, the request body should first need to be buffered in memory, or in a temporary file. We do not consider this approach suitable for general usage -- think of huge multi-gigabyte requests that are filtered, proxied, or otherwise processed on-the-fly by a Falcon application.

That said, if you are confident that your API users will not submit overly large requests, and/or you are checking the `Content-Length` header, you could create your own middleware always buffering the body, for instance:
```python
import sys

import falcon


class BufferedBodyComponent:

    MAX_BODY_SIZE = 1024*1024

    def process_request(self, req, resp):
        req.context.body = b''
        if (req.content_length or 0) > self.MAX_BODY_SIZE:
            raise falcon.HTTPPayloadTooLarge(title='Way too large!')

        req.context.body = req.bounded_stream.read()

    def process_response(self, req, resp, resource, req_succeeded):
        sys.stderr.write('{} {} {} {}\n'.format(
            req.method, req.context.body, req.path, resp.status[:3]))


class Store:

    def on_post(self, req, resp):
        resp.body = 'POSTed text: ' + req.context.body.decode()
        resp.content_type = falcon.MEDIA_TEXT


def handle_error(req, resp, ex, params):
    if isinstance(ex, (falcon.HTTPError, falcon.HTTPStatus)):
        raise

    raise falcon.HTTPInternalServerError(description=str(ex))


app = falcon.API(middleware=[BufferedBodyComponent()])
app.add_error_handler(Exception, handle_error)
app.add_route('/store', Store())
```

Running this as `gunicorn test:app` we can now get some poor man's request logging in the `stderr`. Any unhandled `Exception` would be reported as `500 Internal Server Error`:
```
GET b'' /store 405
POST b'{"json_example": "Hello"}' /store 200
DELETE b'' /404 404
POST b'\x80' /store 500
```

I'll keep this issue open for the time being. We could probably add something like that to our FAQ or Recipes sections.

**Comment by humblewolf** [comment]
I got your point. I was also thinking of doing this via middlewares, but I think it will add latency to the process. My entire point of using flacon instead of flask is because of its fastness/performance. Anyways I am leaving body out of logs as of now.

Thanks for your swift communication. Love to Sweden (huge fan of olofmeister !!!)

**Comment by CaselIT** [comment]
Note that if the body has a content type you can use [Request.media](https://falcon.readthedocs.io/en/stable/api/media.html) to access it, and the media will be cached.

**Comment by vytas7** [comment]
The question itself is not new, it seems.
Merging this issue with https://github.com/falconry/falcon/issues/417
