### ISSUE TITLE
Remove all deprecated behaviors and shims from 3.x

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1853]
Grep the code for "deprecated", etc. and remove relevant code/interfaces. Be sure to include news fragments for each change.

**Comment by abid1998** [comment]
Hello I would like to try this. I am new to falcon so any help/guidance would be appreciated.

**Comment by vytas7** [comment]
Hi @abid1998 , there's already an open PR addressing parts of this: https://github.com/falconry/falcon/pull/1900 , so please check what's left to do so that we don't duplicate efforts.

Also, beware this will only get merged as part of Falcon 4.0, which might take a longer time since we've just begun the 3.x cycle.

**Comment by abid1998** [comment]
Ahh got it.

**Comment by sneznaj** [comment]
should modules that emit DeprecatedWarning be removed too ?
