### ISSUE TITLE
Can't decode URL when preprocessing the request

### ISSUE THREAD

**Issue by cyrillay** [falconry/falcon#1856]
Hello,

I am building a falcon API that receives encoded URLs which contain the following format in query parameters : `eq%3foo` that I would like to preprocess and pass as `eq:foo` before it is routed.

I am using a middleware to try to do the following :  

```python
class RequestPreProcessing:
    def process_request(self, req, resp):
        req.uri = falcon.uri.decode(req.uri)
```

However, this assignment to `req.uri` is blocked and prints a message `can't set attribute`, I guess this attribute is protected.

Do you know how I could achieve this goal ? Am I taking the right approach ?

Help would be very appreciated. Thank you in advance for your answers !

**Comment by vytas7** [comment]
Hi @cyrillay !
As you've correctly noted, `req.uri` is read-only.

[Middleware](https://falcon.readthedocs.io/en/stable/api/middleware.html#middleware) can instead choose to rewrite [`req.path`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.path).

Do I correctly understand that you want to receive the query string baked in the query encoded URI, and convert it to a regular query string in the middleware?
As said, we'd need to twist this logic a bit to assign to `req.path` instead; see my `test.py` below:
```python
import falcon


class RequestPreProcessing:
    def process_request(self, req, resp):
        req.path, _, query = req.relative_uri.partition('?')
        req.context.params = falcon.uri.parse_query_string(
            query, keep_blank=True, csv=False)


class Hello:
    def on_get(self, req, resp, **kwargs):
        resp.media = {
            'msg': 'Hello',
            'kwargs': kwargs,
            'query': req.context.params,
        }


app = falcon.API(middleware=[RequestPreProcessing()])
app.add_route('/hello/{param1}/{param2}', Hello())
```

```
$ http http://localhost:8000/hello/world/eq%3foo

HTTP/1.1 200 OK
content-length: 84
content-type: application/json

{
    "kwargs": {
        "param1": "world",
        "param2": "eq"
    },
    "msg": "Hello",
    "query": {
        "oo": ""
    }
}

```

As you see above, there is a caveat. Even though we overwrite `req.path`, that is used only for routing, but `req.params` are not changed since the initial parsing, so we'd need to store them separately if needed. To that end, we [parse](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.uri.parse_query_string) the encoded query, and store in the [request context](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.context).

Does this shed some light on the subject?

**Comment by cyrillay** [comment]
Hello @vytas7 ,

Thank you very much for your help and answer. 
The way we set up the API makes that the URL is encoded twice : by Apigee, and then by the ALB that we have in front of our API. I notice falcon decodes the URL once, which makes sense, but for this particular case we needed to decode it twice. 

As a workaround, I used your solution of parsing `req.params` then storing them in the request context :

```python
class RequestPreProcessing:
    def process_request(self, req, resp):
      req.path, _, query = req.relative_uri.partition('?')
      query = falcon.uri.decode(query)
      decoded_params = falcon.uri.parse_query_string(query, keep_blank=True, csv=False)
      req.context.params = falcon.uri.parse_query_string(query, keep_blank=True, csv=False)
```

Thanks again for your help.

**Comment by cyrillay** [comment]
Hello @vytas7 ,

Thank you very much for your help and answer. 
The way we set up the API makes that the URL is encoded twice : by Apigee, and then by the ALB that we have in front of our API. I notice falcon decodes the URL once, which makes sense, but for this particular case we needed to decode it twice. 

As a workaround, I used your solution of parsing `req.params` then storing them in the request context :

```python
class RequestPreProcessing:
    def process_request(self, req, resp):
      req.path, _, query = req.relative_uri.partition('?')
      query = falcon.uri.decode(query)
      decoded_params = falcon.uri.parse_query_string(query, keep_blank=True, csv=False)
      req.context.params = falcon.uri.parse_query_string(query, keep_blank=True, csv=False)
```

Thanks again for your help.

**Comment by vytas7** [comment]
You're welcome ;) Happy hacking!
