### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by MajidHeydari** [falconry/falcon#1859]
Why not update the new version?

**Comment by vytas7** [comment]
Hi @MajidHeydari !
That's a very fair call.

Apologies that we've been very busy recently, and just don't manage to find the time required to finalize the stable release :grimacing: 

Stay tuned!

**Comment by MajidHeydari** [comment]
Can Falcon be a better choice for Flask and Django and  FastAPI for AI?

**Comment by CaselIT** [comment]
Sure, but it really depends on what you are doing.

What I mean is that if by AI you mean just expose some endpoints to use some AI models, falcon is a fine choice. I don't have an extensive experience with flask or fastapi but I would guess they are also good choices for this case. If you instead need a complete website then Django may be a better choice, since it has a lot more features that target that.

Falcon leaves you a lot of freedom and allows for a lot of customization, so it should be easy to interac with the ai framework you are using.

Hope it helps

**Comment by MajidHeydari** [comment]
I found out in falcon that admin access is difficult to do and also graphical databases like neo4j cannot do and  have not source.

**Comment by MajidHeydari** [comment]
> I found out in falcon that admin access is difficult to do and also graphical databases like neo4j cannot do and have not source.

**Comment by MajidHeydari** [comment]
> > I found out in falcon that admin access is difficult to do and also graphical databases like neo4j cannot do and have not source.

**Comment by kgriffs** [comment]
When you have a chance, you might post your questions re neo4j in the Gitter user channel; the community is pretty good about helping out:

https://gitter.im/falconry/user

Depending on the solution, it may make sense to create a recipe for the Falcon docs and/or see if anyone would like to kick off a project to create a Falcon add-on.

**Comment by kgriffs** [comment]
rc2 is now available - https://github.com/falconry/falcon/releases/tag/3.0.0rc2

**Comment by kgriffs** [comment]
The final release is now available: https://github.com/falconry/falcon/releases/tag/3.0.0
