### ISSUE TITLE
Got no response on a simple example

### ISSUE THREAD

**Issue by rafaelnovello** [falconry/falcon#1896]
I'm trying to write a simple micro service with falcon and I'm getting no response to my requests. These requests appear on gunicorn log but nothing has returned.

Follow is my code. Could someone helps? I'm using `falcon==2.0.0` and `gunicorn==20.1.0`

```python
import falcon
import json

class ResourceGet(object):
    def on_get(self, req, resp, collection, key):
        data = {"name":"Açúcar","idade":33,"altura":1.74}
        resp.data = json.dumps(data, ensure_ascii=False)
        resp.body = json.dumps(data, ensure_ascii=False)
        resp.content_type = falcon.MEDIA_JSON
        resp.status = falcon.HTTP_200
```

```python
import falcon

from resources import ResourceGet, ResourceList
api = application = falcon.API()

api.add_route('/api/{collection}/{key}/', ResourceGet())
```

**Comment by vytas7** [comment]
Hi @rafaelnovello !
There are a couple of things going on here.

I was running this version of your example:
```python
import falcon
import json


class ResourceGet(object):
    def on_get(self, req, resp, collection, key):
        data = {"name": "Açúcar", "idade": 33, "altura": 1.74}

        # Normally, you don't need to set both body and data.
        # resp.data = json.dumps(data, ensure_ascii=False)

        resp.body = json.dumps(data, ensure_ascii=False)

        # A yet another, more succinct way to set response media:
        # resp.media = data

        resp.content_type = falcon.MEDIA_JSON
        resp.status = falcon.HTTP_200


api = application = falcon.API()

api.add_route('/api/{collection}/{key}/', ResourceGet())
```
I've commented out setting `resp.data` in parallel to `resp.body`; setting both is superfluous, and it could be a source of confusion on its own. See also (Falcon 3.0.0 documentation): [When would I use media, data, and stream?](https://falcon.readthedocs.io/en/latest/user/faq.html#when-would-i-use-media-data-and-stream)

Back to the issue: you are receiving an HTTP 404 response, but that response has no body:
```
$ http http://127.0.0.1:8000/api/items/key01/
HTTP/1.1 404 Not Found
Connection: close
Server: gunicorn
content-length: 0
content-type: application/json
```

Your route was not matched due to a bug in Falcon 2.0; that has now been fixed: https://github.com/falconry/falcon/issues/1544

See also this note in the upcoming Falcon 3.0 docs: [How does Falcon handle a trailing slash in the request path?](https://falcon.readthedocs.io/en/latest/user/faq.html#how-does-falcon-handle-a-trailing-slash-in-the-request-path)

Running with [3.0.0rc1](https://pypi.org/project/falcon/3.0.0rc1/):
```
$ http http://127.0.0.1:8000/api/items/key01/
HTTP/1.1 200 OK
Connection: close
Server: gunicorn
content-length: 49
content-type: application/json

{
    "altura": 1.74,
    "idade": 33,
    "name": "Açúcar"
}
```

So the question is whether you need the precise trailing slash matching here, or not.

If this is not important to your application, you could simply set [`RequestOptions.strip_url_path_trailing_slash`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.strip_url_path_trailing_slash) to `True`, and add your route without the trailing slash (should work on any recent Falcon version such as 1.4, 2.0 and 3.0).

If you need precise trailing slash matching, you might need to upgrade to Falcon 3.0 (or implement a patch yourself in middleware). As hinted above, 3.0 is not yet released at the time of writing this, however [a release candidate](https://pypi.org/project/falcon/3.0.0rc1/) is available.

**Comment by vytas7** [comment]
@rafaelnovello Given the above explanation, I'm inclined to close this as a _duplicate_ of https://github.com/falconry/falcon/issues/1544.
Could you check whether my findings make sense for your application?

**Comment by rafaelnovello** [comment]
Hi @vytas7 I did what you tell me and now it's working! Thank you so much!
