### ISSUE TITLE
More Robust URI specifications

### ISSUE THREAD

**Issue by savorywatt** [falconry/falcon#199]
@kgriffs we spoke on IRC a bit about this so I moved it to an issue so I can keep track of it and we can get some conversation going.

Essentially I want to investigate the acceptance of creating API endpoints that allow you to have multiple variables in them. The main purpose is to expose hierarchical relationships

I'm thinking about how we can do shadow representations of the canonical URI.

E.G.

awesomeblogsite.com/User/1234/Posts/March/I-really-dont-like-green-eggs-and-ham

is a representation of 
awesomeblogsite.com/Post/1234

So we'd need to define two routes

/User/{user_id}/Posts/{month}/{title}
/Post/{post_id}

This would allow the URL to be walkable by the user. Delete the short-url for the post and get page with links to all the posts for that month, delete the month, all the posts for that user.

I'm basing this request off of both my personal observation of how 'others' are implementing RESTful APIs, my understanding of Fielding's ACM paper and what I've read in books and blog articles.

This page has a lot of thoughts on proper URI designing and probably has better examples of what I'm trying to talk about than my blog idea.

http://blog.2partsmagic.com/restful-uri-design/

specifically this pattern appeals to me.

/conversations/conversation-{id}/todo-list-{id}/todo-{id}

**Comment by kgriffs** [comment]
I know this issue is really old, but just wanted to close the loop. Falcon now supports templates such as:

`/conversations/conversation-{conversation_id}/todo-list-{list_id}/todo-{todo_id}`

I started another issue (#584) to discuss supporting alternative routes (such as a shortlink) for the same resource.

**Comment by vytas7** [comment]
It seems this is fully resolved as of Falcon 2.0.
Alternative routes to the resource can now be afforded with the help of [responder name suffixes](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_route).

We do otherwise recognize that more flexible routing is one of the areas where there is room for improvement.
See also this discussion: [Routing improvements](https://github.com/falconry/falcon/discussions/1818).
