### ISSUE TITLE
Error: Elinalinut/Calia-falcon-7b does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by Elinalinut** [falconry/falcon#2165]
So I wanted to make a chatbot using a fine-tuned Falcon 7b model and I don't know why but it doesn't seem to have the config.json file just the adapter_config.json. I would really appreciate it if someone explained to me what I'm doing wrong cause I'm pretty new to this.

**Comment by vytas7** [comment]
Hi @Elinalinut!
It seems you have the Falcon-7B open source language/chat AI model with _this_ Falcon, which is a (also open source) web framework for Python developers :sweat_smile: It can probably be used to write a web API to talk to _that_ Falcon AI, but otherwise these two aren't really related.
