### ISSUE TITLE
Migrate to another code formatter?

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2218]
While `blue` is awesome since it is better tuned for our needs out of the box, and I just :blue_heart: `blue`, it seems that it is [stuck on `flake8` v4.x](https://github.com/grantjenks/blue/issues/78), and it hasn't been updated in two years.
@grantjenks @warsaw If you intend to carry on with `blue`, we'll likely try to keep it, but otherwise we might need to look for alternatives. "Back in Black", or maybe ruff?

**Comment by warsaw** [comment]
Personally, I've made the move to ruff which covers almost all of blue's functionality with the one notable exception, it's handling of [right hanging comments](https://github.com/astral-sh/ruff/issues/7684#issuecomment-2009782586).  I don't intend to maintain blue, but instead help ruff along to full blue parity.

**Comment by vytas7** [comment]
Alright, I see that @grantjenks has moved sortedcontainers to ruff as well, that sums it up I guess.

**Comment by CaselIT** [comment]
I usually use use black in other projects, but I have nothing against using ruff.

@vytas7 do you think it could make sense to try each and post here the commits so that we can look at what change they would introduce?

IIRC black can be configured to not convert `'` to `"`, but that would mean that it would accept both `'` and `"` for strings. Outside that not much changes should happen.

Don't know about what option ruff has, but I gather it's much more than just a code formatter, so it may have more config knobs to tune

**Comment by vytas7** [comment]
Yeah, I'll try to create a prototype with `ruff`. `ruff` is alluring not because just of its brutal speed, but it also has the potential to replace all other tools/plugins that we use (import sorting, etc). I'll need to figure out the required config flags though.

**Comment by warsaw** [comment]
You should be able to configure ruff to be compatible with black or blue, or anything in between.  Like I mentioned earlier, the only thing lacking *for me* at the moment is right hanging comment line up, and there's an open ticket on that issue.
