### ISSUE TITLE
Gate non-breaking releases on large 3rd-party projects that are known to use Falcon

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#259]

**Comment by kgriffs** [comment]
We should add checks for mailman, et al to our CI.

**Comment by vytas7** [comment]
@kgriffs I'm thinking to close this once we re-enable the Hug gate. Hug does fit the bill of a large 3rd-party project.

**Comment by maxking** [comment]
We run tests in a [custom container image](https://github.com/maxking/mailman-ci-runner), so it should be easy to setup with CI anywhere, I guess most CI providers support that. Our tests are not that fast right now, the test infra does needs some love to support parallelization/pytest. Our fastest test runs in 7 odd minutes (https://gitlab.com/mailman/mailman/-/jobs, sqlite jobs are probably easiest to run), and looking at the Actions tab for Falcon, it seems like typical test runs as 5 odd minutes, so it would cause ~2min slowdown per-test when run in parallel.

Although, instead of using  a CI gate, you could also run it on main/master branch, and that way you could trace if anything will cause downstream issues post-merge. 

Wiring local branch is easy with tox, we can create a new tox env for falcon testing uses an env variable with commit hash and you add dependency on `git+https://github.com/falconry/falcon@{COMMIT_SHA}` for that env.

I am happy to help wire things up.

**Comment by vytas7** [comment]
That sounds awesome @maxking, those tests+image are really streamlined :100:. I've just tried to clone `mailman` into a container using your image on my machine, and `tox -e py38-nocov` ran in 4m 19s including `pip` installation, so maybe it could even be suitable for every PR. I think Actions' machines are beefier than GitLab's, although as with all heavily virtualized stuff it fluctuates wildly.

Running on my machine, 3 tests failed while trying to bind on IPv6, and from what I gather it might be an issue even on Actions: https://github.com/actions/virtual-environments/issues/668 (although I haven't dug too deeply whether it was just outbound traffic, or the Docker host's config in general).

But otherwise yes, I meant CI in a general sense; it could be just CI on the `master` branch as we do for tests on emulated architectures, taking some 20-30 minutes (in order to verify that our C/Cython code is endian-agnostic and builds on a wide range of architectures).

**Comment by vytas7** [comment]
@maxking for reference, I've glued something together now: https://github.com/falconry/falcon/pull/2031#issue-1146006778
