### ISSUE TITLE
Default to JSON for error serialization, rather than XML

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#302]
Based on community feedback, default to JSON rather than XML, when the client accepts both media types.

**Comment by Khazbs** [comment]
Looks like Firefox prefers XML by default... Well, we'll have to live with it

**Comment by CaselIT** [comment]
This is common also to chrome when using the browser to make the request.

I think it's because, at least for me, the `Accept` header is something like `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`. xml is listed before */*, while json is not, so that's what is returned by falcon.

If you were to use only `*/*` in `Accept` json is preferred. Not sure if both are listed, but I think json also in this case is listed
