### ISSUE TITLE
Validation helpers

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#31]
Validation helpers that throw appropriate HTTP exceptions for URI params as well as the body (validate XML, JSON).

Would this be better as a separate project/add-on?

**Comment by vytas7** [comment]
I'm going to close this for now since it has been largely superseded by the organic growth of the framework; query parameters have many `req.get_param_as_*()`, and for body there is optional `jsonschema` support.

All types of validation are admittedly still spartan, but in line with Falcon's minimalist nature, this is probably better implemented as a separate add-on, or an optional integration with a 3rd party library (like `jsonschema`).
