### ISSUE TITLE
Investigate streaming use cases and how they might be supported in Falcon

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#349]
For example: http://blog.miguelgrinberg.com/post/video-streaming-with-flask

**Comment by vytas7** [comment]
Moving this to a discussion since the scope is quite broad, and it's probably better suited for a third party component or a blog post.
As of 3.1, static routes will support streaming simple HTML5 videos with `Range` requests (https://github.com/falconry/falcon/issues/1857). We also have some recipes how to stream content [on-the-fly](https://falcon.readthedocs.io/en/stable/user/recipes/output-csv.html#streaming-large-csv-files-on-the-fly).
