### ISSUE TITLE
Decoding the query string before parsing it is problematic

### ISSUE THREAD

**Issue by elishacook** [falconry/falcon#369]
Let's say I wanted to encode some JSON, like `{"foo":1,"bar":2}` in a query param. Usually I would encode this value and pass it in the URL like this, `/my/api?skidoo=%7B%22foo%22%3A1%2C%22bar%22%3A1%7D`. The way things currently work, the whole query string will be decoded and then parsed by splitting at commas. This results in a `skidoo` param with two values `'{"foo":1'` and `'"bar":1}'`.

If the query string were parsed and then each key and value decoded the result would be a single `skidoo` param with the value ``'{"foo":1, "bar":1}'`.

**Comment by rsyed83** [comment]
That sounds reasonable.  Perhaps the existing behavior can be kept in a method should a user desire this behavior, but default behavior should decode the query string without assuming the values are comma-delimited.

**Comment by kgriffs** [comment]
Yeah, so the issue isn't so much that the entire query string is being decoded in a single pass, but that each value is being split by comma. We could use RequestOptions to toggle splitting values on commas, and turn it off by default. That would be a breaking change, but it would be easy for anyone encoding lists into values to turn it back on and be back in business.

**Comment by rogerbush8** [comment]
I don't think you can decode in one pass, and I've never seen it done that way.  The reason is that percent encoding is meant to take special characters with reserved meaning and turn that reserved meaning off.  It's a form of escaping, much like "\n" prevents the carriage return from going to the next line.  Therefore if I have an encoded "&" for example, decoding in one pass will mixup the special (non-escaped) & and escaped &.  You will split on all of the escaped &, which would be an error.

http://en.wikipedia.org/wiki/Percent-encoding

There is a nice side to all of this which is that if you slightly extended the special characters to include ",", then an escaped "," would not split (internal split to array, not param split).  This would allow things to mostly work as-is, with the small additional documentation that "," should not be percent encoded if their special split behavior is desired.

**Comment by rogerbush8** [comment]
You may, of course, still have to have a flag on the off case that someone is percent encoding and their "," turned off would break.  However, you're at .3 so I'd think this type of thing can be squeezed through without the annoying flag.

**Comment by rogerbush8** [comment]
I've seen lots of encoding/decoding errors in complex params (on both sides:  developers implementing, and frameworks).  With the niche falcon occupies, it would be great if parameter decoding/encoding just worked flawlessly.  I realize this is true spec-grunginess at it's finest, but...

Here's a pretty thoughtful article by someone who tried to get all of this absolutely correct.  I only fact checked some of it (the parts on escaping special characters, and some other parts) and it seems right on.

http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding

**Comment by kgriffs** [comment]
There's a PR (#461) to address this. Love to get some more eyes on it.

**Comment by rogerbush8** [comment]
OK, commented in the ticket.  I'll look over the code when I get a chance.
In a nutshell, I suggest decoding very last (it's the only possible right thing to do).
This means you must split twice, once using literal "&" (split to name=value pairs),
and then subsplit the value on literal "," to get induced array values.

Once you've done that, you can iterate through this mess and decode each fragment
(i.e. each value, or the param name).  Not decoding the individual array values (induced
by ",") means you are treating these values differently than scalars - why would you want
that? (answer: you don't).

Thanks for jumping on this so quickly, you guys rock!
