### ISSUE TITLE
Request hangs if method is GET and content-type is application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by dukedougal** [falconry/falcon#407]
For some reason I have some software that sends content-type=application/x-www-form-urlencoded with GET requests.  It shouldn't, but that's not important.

Such requests hang, whereas the content-type should just be ignored.

The reason appears to be in request.py line 258

        if (self.content_type is not None and
                'application/x-www-form-urlencoded' in self.content_type):
            self._parse_form_urlencoded()

I think it probably should make the above conditional upon either the request METHOD being PUT or POST or PATCH maybe.  Or some other solution.

**Comment by kgriffs** [comment]
Hmm, good catch. I'll add this to the 0.2 milestone so we can get it fixed before RC1.

**Comment by kgriffs** [comment]
If it is hanging, I suspect this line of `_parse_form_urlencoded`:

```python
body = self.stream.read()
```

Normally GETs do not have bodies, so the stream in your case is probably empty. That stream is normally just set directly to the WSGI `environ['wsgi.input']`. With that in mind, I'd like to find out what WSGI container you are using so I can try to reproduce. I know that uwsgi and gunicorn pass a nonblocking, file-like object as `environ['wsgi.input']`.

BTW, we'll likely be changing form data to be parsed on-demand in the next release, rather than automatically as it is done now. That way, if you have a case where you want to parse the request in a different way, you can do that.

**Comment by dukedougal** [comment]
I'm using gunicorn in development, probably uwsgi in production but I haven't decided yet.

As mentioned at the top of this thread, the problem is solved by just checking the request method before attempting to parse form data, and only parsing if its a method that support form data, which GET obviously doesn't.

**Comment by kgriffs** [comment]
UPDATE: I've scheduled this for 0.3. It will need a test to repro. When working on #418, care must be taken to only expect body data when the request is a POST; if it is a GET, the form fields are assumed to be encoded in the URL's query string.

**Comment by csojinb** [comment]
I can pick this up

**Comment by csojinb** [comment]
@dukedougal I am unable to reproduce this by GET-ing with `application/x-www-form-urlencoded` content-type against a simple hello-world route running on gunicorn. Can you please give some more details to reproduce the problem?

Without reproducing, I cannot tell whether your suggested solution, or any other, will actually fix it. And, I'd prefer to fix the underlying issue if it can be found, rather than blindly side-stepping a particular path without knowing why.

**Comment by jmvrbanac** [comment]
We cannot currently reproduce this issue. @dukedougal could you provide more information about how to reproduce this issue? Thanks!

**Comment by bcattle** [comment]
@kgriffs I get the hang on `body = self.stream.read()` for well-formed JSON (an example being `'{"username": "test-username", "password": "password"}'`. 

Instead calling `body = req.stream.read(req.content_length)` appears to have fixed the problem. It's apparently hanging indefinitely because it never receives EOF?

**Comment by kgriffs** [comment]
Thanks @bcattle for the report. What WSGI server are you using to host your app? I'd like to try reproducing it myself to help track this down.

**Comment by bcattle** [comment]
I'm using [werkzeug](http://werkzeug.pocoo.org/docs/0.11/serving/):

    from werkzeug.serving import run_simple
    run_simple('localhost', 8000, app, use_reloader=True)

Internally, wekzeug is using [`BaseHTTPServer.HttpServer`](https://docs.python.org/2/library/basehttpserver.html#BaseHTTPServer.HTTPServer) from the standard library. I'm on PyPy 2.6.0 on OSX.

**Comment by orcsly** [comment]
I'll have a look at trying to reproduce this one.

**Comment by orcsly** [comment]
Just an update, have not been able to reproduce this with werkzeug with PyPy 2.4 on OSX.

@bcattle do you have a sample project that demonstrates this issue?  Thanks.

**Comment by orcsly** [comment]
Actually managed to reproduce with werkzeug and having the auto_parse_form_urlencoded options set to True.

**Comment by kgriffs** [comment]
Confirmed. I also was able to reproduce, but only when using run_simple(), not when manually pumping the requests via handle_request().
