### ISSUE TITLE
Respect Content-Type header when encoding unicode bodies

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#422]
Currently, if req.body is set to a unicode string, the framework always encodes it as UTF-8 in the response. For correctness, we should respect alternate encodings when they are specified in the Content-Type header for the response.

**Comment by lwcolton** [comment]
Can you explain this a little more?  Would this just be if the content-type is set to text/<anything>, then charset is used to decide how to encode the charset?  http://www.w3.org/Protocols/rfc1341/7_1_Text.html

**Comment by kgriffs** [comment]
According to https://tools.ietf.org/html/rfc2046#section-4.1.2 :

> Other media types than subtypes of "text" might choose to employ the charset parameter as defined here

For example, RFC 7303 defines multiple charsets for the XML media type, e.g.:

> Content-Type: application/xml; charset=utf-16

**Comment by vytas7** [comment]
I'm going to close this issue since it hasn't really attracted much attention, and it feels like it should be responsibility of the respective media handler. For instance, JSON is standardized to almost always use UTF-8 (or just ASCII by escaping the entities).

[`resp.text`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Response.text) is documented to encode in UTF-8, simple and clear.
For more advanced handling of text as media, see also https://github.com/falconry/falcon/issues/2037
