### ISSUE TITLE
Add support for setting the realm to the HTTPUnauthorized class

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#430]
Currently the class recognizes a *scheme* kwarg that can include a realm string, but IMO it would be better to make this explicit. 

See also RFC 7235.

**Comment by mcmasterathl** [comment]
I can work on this.

@kgriffs it looks like the RFC says you can have multiple comma-separated challenges in a single header, or multiple headers. Each challenge is a scheme and zero or more comma separated key=value pairs. Also, optionally, the key=value pairs could be base64 encoded.

In order to implement all of this, I suggest the following:
* Add a new kwarg for accepting a list of valid challenges. Each challenge would need a "scheme" item, and the other items would be used in comma-separate key=value format.
* Add a new kwarg to control whether to base64 encode the key=value options
* Add a new kwarg to control whether to set a single or multiple WWW-Authenticate parameters

I'm not sure whether this is the best way to implement though, so any feedback before I dive in would be appreciated. I'm also not sure what backwards-compatibility would look like, or if you want to drop it since this is a future milestone feature.

**Comment by kgriffs** [comment]
@mcmasterathl  Sounds good. I think someone else started work on this, and was taking the approach of just taking a list of opaque challenge strings. So it just leaves the formatting of each challenge to the caller. This is probably OK for 0.3, but we may want to do something more sophisticated (as recommended above) for 0.4 or 0.5. 

Let's see if a PR comes in for this and then we may want to create an additional issue to look at doing more, as previously mentioned.

**Comment by ueg1990** [comment]
hey Kurt, i will try and send a PR by today. After that you can let me know if you need anymore changes on that.
