### ISSUE TITLE
Leave headers with case sensitive names

### ISSUE THREAD

**Issue by berlotto** [falconry/falcon#437]
All names of headers dict are in UPPERCASE.

**Comment by kgriffs** [comment]
Unfortunately, this is an example of a leaky abstraction. Falcon receives the headers through the WSGI environ dict, at which point the names have already been uppercased. We could change ``req.headers`` to return titlecased names, but that would require extra processing. 

Since header names are defined to be case-insensitive in the HTTP RFCs, I haven't made this work a high priority up to this point. That beings said, if someone would like to submit a PR that we can benchmark, and it doesn't add a significant amount of overhead, I wouldn't be opposed to merging it.

**Comment by kgriffs** [comment]
Subsumed by #420
