### ISSUE TITLE
Error representation strangeness

### ISSUE THREAD

**Issue by b6d** [falconry/falcon#452]
Hello,

I'm using falcon 0.2.0rc2, and I've noticed some behaviour regarding error representation that I don't understand:

1) An instance of `HTTPNotFound` without a description claims to have no representation even if it does have a title. This differs from the behaviour of `HTTPError`:

``` python
>>> import falcon
>>> falcon.HTTPError(falcon.HTTP_404, title='Not found.').has_representation
True
>>> falcon.HTTPNotFound(title='Not found.').has_representation
False
```

2) An error that claims to have no representation does not result in an empty response body even though the documentation states otherwise (http://falcon.readthedocs.org/en/0.2.0rc2/api/errors.html#HTTPError.has_representation). This means that a response body that is set earlier is sent to the client (instead of an empty body)

``` python
#!/usr/bin/env python3
import falcon
from wsgiref.simple_server import make_server

class Foo:
    def on_get(self, req, resp):
        resp.body = 'I get sent to the client.'
        raise falcon.HTTPNotFound(title='Not found')  # has_representation is False

app = falcon.API()
app.add_route('/foo', Foo())

httpd = make_server('', 5000, app)
httpd.serve_forever()
```

I'm not sure if those are bugs, but they seemed unintuitive enough to me to report them here.

[edit: corrected wrong error code in example 1]

**Comment by b6d** [comment]
Regarding 1): I just realized that this is intended and documented behaviour (`HTTPNotFound` subclasses `OptionalRepresentation` which sets `has_representation` *only* if there is a description)

**Comment by kgriffs** [comment]
I agree that this behavior is confusing. It may make more sense to abandon `OptionalRepresentation` in favor of simply adding some additional error classes that don't change their semantics based on what kwargs are passed in. I.e.:

```py
class HTTPNotFound(NoRepresentation, HTTPError):
    def __init__(self):
        super(HTTPNotFound, self).__init__(status.HTTP_404)

class HTTPNotFoundVerbose(HTTPError):
    def __init__(self, title=falcon.HTTP_404, description=None, **kwargs):
        super(HTTPNotFoundVerbose, self).__init__(
            status.HTTP_404,
            title=title,
            description=description,
            **kwargs
        )

class HTTPMethodNotAllowed(NoRepresentation, HTTPError):
    def __init__(self):
        super(HTTPNotFound, self).__init__(status.HTTP_405)

class HTTPMethodNotAllowedVerbose(HTTPError):
    def __init__(self, title=falcon.HTTP_405, description=None, **kwargs):
        super(HTTPMethodNotAllowedVerbose, self).__init__(
            status.HTTP_405,
            title=title,
            description=description,
            **kwargs
        )
```

**Comment by vytas7** [comment]
A practical example how users can get confused (myself included :confused: ), because of the combination of this issue, https://github.com/falconry/falcon/issues/777 , and probably others.

As a user, I may want to style/customize all error responses from my API to look and feel the same.
This includes methods raised by the API and the router as well.

Currently, a potential solution could look like:
1. Pass both title *and* description to make sure ``OptionalRepresentation``-derived errors show up at all, and/or derive custom classes that override the effects of ``OptionalRepresentation``.
2. Add a custom serializer to customize and style as desired.
3. Add a sink to suppress ``404``s and ``405``s from routing, and raise own exceptions and/or ensure title/description are present, see 1.

This might be perceived as somewhat clunky, would be cool to improve and document this case.

**Comment by kgriffs** [comment]
I think that for 2.0 we should certainly fix the issue where custom serializers are not always called (I broke this out as a separate issue here: https://github.com/falconry/falcon/issues/1422).

As for switching to always return a representation/body for errors by default unless explicitly forbidden by the RFCs, we should discuss that further and make a decision for Falcon 3.0.

**Comment by CaselIT** [comment]
I think that by default we could do away with the `has_representation` and always return a representation, since I don't think the complexity it introduces are worth the benefit. This would also avoid the problem that the body that is set before the error gets sent back.

If an user wants to customize this behavior he can specify a custom error serializer that do something like this. This custom serializer should also handle the case of the body set before the error if he prefers to not return a representation in some cases. A note should probably be added regarding this in the documentation.

After https://github.com/falconry/falcon/pull/1655 all errors have optional representation

**Comment by kgriffs** [comment]
@CaselIT We can go ahead with the approach you outlined, with the caveat that we hard-code the special case of HTTP status codes that are explicitly forbidden by the RFCs to have a body. I don't think we should allow a body regardless of whether or not a custom error serializer is in play. 

@vytas7 Thoughts?

**Comment by CaselIT** [comment]
Is there a list of http statuses that cannot have a body?
Also how do you suggesting disallowing custom serializers from adding a body?
Should be just not call them in case of a status that require no body?

**Comment by kgriffs** [comment]
TBH, I just realized I was thinking of non-error status codes that would not be applicable in this case. 🤦‍♂ 

```py
_BODILESS_STATUS_CODES = frozenset([
    status.HTTP_100,
    status.HTTP_101,
    status.HTTP_204,
    status.HTTP_304,
])
```

**Comment by vytas7** [comment]
AFAICT we short-circuit the above mentioned "bodiless" status codes in the `App` not to render any body, so it's probably a non-issue either way.
And we do not have any subclasses of `HTTPStatus` for any of the above codes.
We may discuss adding `HTTPNotModified` in the future to simplify processing, however, the `App` clause would still cover it implicitly.
