### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#460]
Add support for enabling HSTS?

See also: http://tools.ietf.org/html/rfc6797

Perhaps this could simply be a flag or something that is enabled in API options, then applied to every response?

**Comment by bryson** [comment]
Wouldn't this be better set by the webserver, rather than the framework? For example, in Nginx's config: `add_header  Strict-Transport-Security "max-age=31536000; includeSubdomains;";`

**Comment by oscarcp** [comment]
I'm always of the opinion that HSTS has to be enforced by the web server instead (nginx, Apache...) but in the case of allowing Falcon to send the HSTS header, your approach would be the best, habing an extra parameter on the API class to activate it.

**Comment by kgriffs** [comment]
@oscarcp Actually, now that you say that, I wonder if this would be considered a "hop-by-hop" header, and therefore WSGI apps shouldn't be touching it anyway...

**Comment by oscarcp** [comment]
I've been digging through this for a couple hours. It seems that WSGI apps are not meant to handle it, but there is a bunch of apps for flask and django that handle HSTS on a URL basis, which is odd, because the premise of HSTS is to force HTTPS connection on the whole domain while the HSTS set is alive on the browser (default: 1 year), rendering those apps useless after the first request.

My bet is leaving this out of Falcon, let it be handled by the webserver unless we find a use case that requires it (in which case can be also implemented via middleware that sets the header)

In my personal use case enforce HTTPS at three points: first, a redirect in nginx from http to https, then HSTS also in nginx and last a middleware (I'm using falcon 0.2) that enforces HTTPS connection or the application doesn't respond.

**Comment by kgriffs** [comment]
Ah, I wonder if it would be useful then to just have a simple "require HTTP" feature in the framework that does what your middleware does? We'd have to make it very clear that it is only a "last resort" and that doing the redirect and HSTS stuff is the first line of defense.

**Comment by oscarcp** [comment]
That's actually a good idea, having an option that forces HTTPS communication is quite common in backends :)

**Comment by kgriffs** [comment]
Note: We'll need to make sure our HTTPS detection logic takes into account `X-Forwarded-Proto` as well as the `Forwarded` header ([RFC 7239](https://tools.ietf.org/html/rfc7239)).

**Comment by kgriffs** [comment]
NOTE: The developer is responsible for enabling this flag in production deployments. This acts as a last-ditch check in case HTTP is accidentally allowed throw at the LB/server layer. Docs should strongly recommend additional layers of enforcement, such as HSTS + redirect from HTTP to HTTPS.

**Comment by kgriffs** [comment]
@paul291 will probably take this one

**Comment by kgriffs** [comment]
Let's make a decision on where this should live and finish this up in the 1.1 timeframe. I think it should either live as an add-on under Paul's GH account, or if he is not interested in maintaining it, maybe we can bring it under falconry.

**Comment by kgriffs** [comment]
See also: #858

**Comment by kgriffs** [comment]
Completed as: https://github.com/falconry/falcon-require-https
