### ISSUE TITLE
Define and document guidelines for Talons authors

### ISSUE THREAD

**Issue by sebasmagri** [falconry/falcon#468]
The output of this task would be an addition to #467 and should hold more specific guidance and API documentation references for those wanting to create middlewares, extensions or _talons_.

Some topics to consider:
- [ ] Coding should follow Falcon's style and guidelines. Specially wrt testing, docs and coding style.
- [ ] Improve middleware and hooks documentation with additional bits for extension authors
- [ ] Guidelines for naming and packaging modules extending Falcon, making it easy for people to find them on PyPI
- [ ] Communication and announcement of new extensions (i.e. [ANN] in the mailing list or PRs to falconframework.org)

**Comment by vytas7** [comment]
Hi @sebasmagri !
I'm going to unfortunately close this since the [latest Talons release](https://pypi.org/project/talons/) on PyPi is now 5 years old, and repositories on GitHub are not much ahead either.

I tried cloning them, and they seem to have fallen a fair bit behind both the latest Falcon interfaces, as well as behind the Python tooling ecosystem (`tox`, `pip` etc).

@sebasmagri @jaypipes @swistakm 
Let us know if there is any new Talons development planned, happy to reopen this issue in that case!

**Comment by swistakm** [comment]
I don't plan any talons development

**Comment by jaypipes** [comment]
Yeah, sorry @vytas7 there has not been any development on Talons for many years.

**Comment by vytas7** [comment]
Thanks for chiming in guys, I'll leave this closed for the time being then.
It seems Talons was a cool project back in the day :wink:
