### ISSUE TITLE
Support checking Origin against Host

### ISSUE THREAD

**Issue by lwcolton** [falconry/falcon#515]
According to the W3C  http://www.w3.org/TR/cors/#resource-security

Resources should check the Origin header against the Host header, to protect against a DNS binding attack.  Falcon should provide an option for this.  I will implement it when I manage to get CORS done, unless someone else wants to take a stab.

**Comment by oscarcp** [comment]
I just did that for my project, it's not really the best option, but you can take a look here: https://github.com/clione/sikre/blob/master/sikre/middleware/headers.py#L29

It allows CORS for any well formed domain, excluding any other input.

**Comment by kgriffs** [comment]
> That is, make sure that the host name provided by that header matches the host name of the server on which the resource resides. This will provide protection against DNS rebinding attacks.

I suppose we could modify `falcon.API` to accept a name that would be checked against the Host header for every request. However, in theory HTTPS mitigates this attack already, since browsers perform hostname verification on the cert. But for other types of user agents, the story is mixed; historically, many HTTP client libraries have not enabled hostname verification by default. Perhaps this would be a useful "just in case" feature?

Thoughts?

**Comment by lwcolton** [comment]
This should probably go in falcon-cors since it looks like this check is
required by the w3c's CORS spec

**Comment by vytas7** [comment]
Closing this since (as @kgriffs also pointed out) the real checking against the host is done as part of the HTTPS domain name validation against a TLS cert, and HTTPS is now getting more and more ubiquitous across the web. Otherwise it is really easy to forge whatever `Host` / `Origin` by simply setting the corresponding header.

This is still useful for CORS, however AFAICT both Falcon's built-in [`CORSMiddleware`](https://falcon.readthedocs.io/en/stable/api/cors.html#falcon.CORSMiddleware) and [`falcon-cors`](https://pypi.org/project/falcon-cors/) now support supplying a list of allowed origins.
