### ISSUE TITLE
Swagger and falcon?

### ISSUE THREAD

**Issue by weldpua2008** [falconry/falcon#520]
Hello,
I need document api. Maybe there is solution for this?

Thanks.

**Comment by kgriffs** [comment]
We don't have support for Swagger directly in the framework, but someone might have written a third-party package.

@jmvrbanac Have you come across anything along these lines?

**Comment by jmvrbanac** [comment]
Apologies I completely missed that I was tagged in this issue. No I haven't. I have spent some time thinking about this, but unfortunately, haven't found an easy way to properly generate the documentation.  Route information is easy, it's determining the possible status codes, return values, parameters, and corresponding documentation strings for it all which is a bit painful. I would love to have a solution for this, but a good one hasn't come to mind yet.

**Comment by lwcolton** [comment]
Swagger isn't something that would integrate directly with Falcon, because like @jmvrbanac said it needs information on parameters, database schema, return values, etc.  At HurricaneLabs we are developing a library called Cujo, which builds on top of Falcon and one day will have swagger support.  I will open an issue on our side for this.

**Comment by lwcolton** [comment]
https://github.com/HurricaneLabs/cujo/issues/8

**Comment by ayushidalmia** [comment]
Can anyone point to anything useful related to swagger and falcon?
