### ISSUE TITLE
Missing Content-Type on 404 Response

### ISSUE THREAD

**Issue by RonRothman** [falconry/falcon#689]
Greetings,

I've started [testing my webapps with wsgiref.validate](http://blog.dscpl.com.au/2015/05/returning-string-as-iterable-from-wsgi.html), and discovered that Falcon's 404 responses (and possible others) don't conform to the WSGI spec.  The `Content-Type` header is required but not present.

This script demonstrates:

    import falcon
    from webtest import TestApp
    import wsgiref.validate

    # the app -- note that it has no routes so all GETs will return 404
    app = falcon.API()

    # wrap in validator middleware
    app = wsgiref.validate.validator(app)

    # wrap in test middleware
    app = TestApp(app)

    # provoke a 404
    resp = app.get('/doesntexist', status=[404])

Output is:

    Traceback (most recent call last):
        <...snip...>
      File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 247, in __call__
        start_response(resp.status, headers)
      File "/usr/lib/python2.7/wsgiref/validate.py", line 167, in start_response_wrapper
        check_content_type(status, headers)
      File "/usr/lib/python2.7/wsgiref/validate.py", line 419, in check_content_type
        assert_(0, "No Content-Type header found in headers (%s)" % headers)
      File "/usr/lib/python2.7/wsgiref/validate.py", line 129, in assert_
        raise AssertionError(*args)
    AssertionError: No Content-Type header found in headers ([('content-length', '0')])

FYI, as a sanity check, I ran the same test using Bottle in place of Falcon, and it conforms (sends Content-type with the 404 response.)

I'm assuming that we want to be compliant with the WSGI spec, in which case this is a bug. Happy to submit a PR if you point me in a recommended direction to patch.  (Set Content-type in `falcon/responders.py:path_not_found` ?)

**Comment by kgriffs** [comment]
Hi @RonRothman, thanks for the report. I was able to reproduce this for 404 and 204, as well as a 100 (although strictly speaking, a WSGI app probably shouldn't ever return a 100 status). Based on my understanding of the HTTP RFCs, the Content-Type isn't strictly required in these cases, but I supposed it doesn't hurt anything if we want to include it in order to pass the wsgiref validator. 

`falcon.API()` currently skips setting the Content-Type header per this code block:

https://github.com/falconry/falcon/blob/master/falcon/api.py#L233-L235

I suppose we could change it to always provide a default media type to `resp._wsgi_headers()` that will be used unless explicitly set by a responder. @RonRothman what do you think?

In the context of a 404, if the media type needs to change depending on the resource requested, the app can register a custom error handler for `falcon.HTTPNotFound` (depends on #655).

**Comment by kgriffs** [comment]
I put of a proof of concept that includes a fix: #698
