### ISSUE TITLE
Can Falcon dispatch to a callable based on any property of a request, not just request method (GET/POST etc)?

### ISSUE THREAD

**Issue by dukedougal** [falconry/falcon#709]
accept headers, cookies, query strings, etc.

**Comment by kgriffs** [comment]
Currently `API._get_responder()` looks up the responder  based on the path and HTTP method in the request. You could inherit from `API` and override `_get_responder()` to make it more flexible. Depending on what you need to do, a sink may also work.

**Comment by dukedougal** [comment]
OK.  Although it would be nice if it was kinda built in as a core feature without need to do sinks or overrides.

**Comment by vytas7** [comment]
I'm going to close this since it's unlikely that we are going to support dispatching based on _any_ property of a request in the default router.
However, since https://github.com/falconry/falcon/issues/967, routers get access to the full `req` object, so a custom router can now be used to achieve just that.

A subset of this issue, routing based on query string parameters, is tracked in https://github.com/falconry/falcon/issues/838.
