### ISSUE TITLE
Implement CORS

### ISSUE THREAD

**Issue by luanalbineli** [falconry/falcon#713]
Hi Falcon Team,

It's my first time using this API, and I'm having a problem with CORS.
I implemented it using a middleware with a process_request:

```
response.set_header('Access-Control-Allow-Origin', '*')
response.set_header("Access-Control-Expose-Headers: Access-Control-Allow-Origin")
response.set_header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept')
```

But when an error occurs (an internal server error, like a key beeing accessed not existing in the dict), my custom header (to allow CORS) is not sent with the response error (500).

Am I doing something wrong?

Thanks,
Luan.

**Comment by dgonzo** [comment]
@luanalbineli not sure if you already found this but I've been tackling similar and found this:

[falcon-cors](https://github.com/lwcolton/falcon-cors)

With the reference implementation of CORS happening here:

https://github.com/lwcolton/falcon-cors/blob/master/src/falcon_cors/__init__.py#L230

@lwcolton appears to be doing a solid job.

**Comment by luanalbineli** [comment]
Hi @dgonzo ,

Thanks for your reply.
I think that I did not explain my problem right. I used falcon-cors/custom headers, but the problem is when an error raises in the middle of the request process. For example, when I try to access a key in a dict without check if the key really is there, an error raises, and falcon does not give back the falcon-cors headers/custom headers of the response. Consequently, Chrome (I'm building a Ionic App) gives me a Access-Control-Allow-Origin error.

Resuming, when an unexpected error occurs, falcon does not append my custom header in the response.

Thanks,
Luan.

**Comment by lwcolton** [comment]
@luanalbineli I think what @dgonzo meant is that I have released a semi-official falcon-endorsed CORS package to handle CORS.  Before asking for help from me or the falcon framework, you should replace your custom CORS code with the falcon-cors package.  Make sure to read the documentation.  If you are still having a problem afterwords I will be able to help you troubleshoot it.

**Comment by luanalbineli** [comment]
Hi @lwcolton , thanks for your reply.

As i said, i used falcon-cors, but it gives me the same result: when an unexpected error ocurs, falcon does not append the access-control-allow-origin header in the response.

**Comment by swistakm** [comment]
@luanalbineli this is the common issue for any of the application-level implementations of CORS. Usually it does not make a problem for people since failed XHR request response is useless in the same way as a it is when proper `access-control-*` headers are missing. Usually people forget that if CORS headers are not added to error response too, it makes a lot harder to debug issues on the browser. I did not look closer at the sources of falcon-cors but I think this could be oversight that way.

This is the reason why people usually manage CORS setup on a higher level of the application stack. If you use nginx or apache in front of your falcon-powered service then you can easily configure vhost to set specific headers even for error responses (at least in newer versions of nginx). There gives of course less a bit less of the flexibility becasue it is harder to manage per-resource settings. Still you can do a lot of things with good web server (nginx ftw!). 

Consider using above approach as a solution to your problem because in practice it is works more reliable. Of course if what you want to achieve are the real HTTP error responses in browser logs instead of generic cors-related issue.

**Comment by admiralobvious** [comment]
@luanalbineli I know this is pretty old but we ran into that issue as well and came up with the following workaround of making your adding your own error_handler which correctly run our middleware and add CORS headers:

@swistakm That works if you're running your own load-balancer but we're using Google Cloud's HTTP L7 load-balancer which just swallows the 500s and return a 502 with Falcon's default 500 behaviour because all it sees is that the backend closed the connection.

```
def handler(ex, req, resp, params):
    if not isinstance(ex, falcon.HTTPError):
        raise HTTPError(500, str(ex.message))
    else:
        raise ex

api = falcon.API()
api.add_error_handler(Exception, handler)
```

Before:
```
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 141
Content-Type: text/html

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
```

After:
```
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Date: Thu, 24 Nov 2016 22:10:06 GMT
Server: gunicorn
access-control-allow-credentials: true
access-control-allow-headers: Origin, Authorization, Content-Type, X-Requested-With
access-control-allow-methods: GET, PUT, POST, DELETE
access-control-allow-origin: *
content-length: 99
content-type: application/json; charset=UTF-8
vary: Accept

{
    "description": "global name 'asd' is not defined",
    "title": "500 Internal Server Error"
}
```

**Comment by lwcolton** [comment]
@luanalbineli @swistakm   Sorry for my inadequate previous response.  It is not falcon-cors swallowing the error here, but falcon framework itself.  falcon-cors middleware processes CORS headers regardless of whether the resource raised an exception.  If an error handler has not been added to the falcon API, falcon will stop processing when an exception which is not an instance of falcon.HTTPError is raised.  Adding an error handler like @admiralobvious suggested will allow processing to continue when non-http exceptions are raised.  I changed one line in that example, to raise HTTPInternalServerError:

```python
def handler(ex, req, resp, params):
    if not isinstance(ex, falcon.HTTPError):
        raise falcon.HTTPInternalServerError(description=repr(ex))  # Changed this to use falcon's error and repr() instead of str()
    else:
        raise ex 
```

In the future you can create cors-related issues on the falcon-cors project:  https://github.com/lwcolton/falcon-cors

**Comment by lwcolton** [comment]
@kgriffs Ready to close this
