### ISSUE TITLE
URL route compile breaks when param name is changed

### ISSUE THREAD

**Issue by bcattle** [falconry/falcon#794]
Adding this route works:

    app.add_route('/v/{video_uuid}', endpoints.GetDeleteVideoEndpoint())

Adding the same route with a longer variable name produces an error:

    app.add_route('/v/{video_uuid_or_short_id}',  endpoints.GetDeleteVideoEndpoint())

The error is

> Traceback (most recent call last):
>   File "<builtin>/app_main.py", line 75, in run_toplevel
>   File "run-server.py", line 5, in <module>
>     from server import app
>   File "/Users/bryan/Documents/koowalla-backend/app/server.py", line 61, in <module>
>     app.add_route('/v/{video_uuid}/likes',   endpoints.LikingUsersByVideoEndpoint())
>   File "/Users/bryan/Documents/koowalla-backend/app/venv_pypy/site-packages/falcon/api.py", line 323, in add_route
>     **kwargs)
>   File "/Users/bryan/Documents/koowalla-backend/app/venv_pypy/site-packages/falcon/routing/compiled.py", line 84, in add_route
>     insert(self._roots)
>   File "/Users/bryan/Documents/koowalla-backend/app/venv_pypy/site-packages/falcon/routing/compiled.py", line 64, in insert
>     insert(node.children, path_index)
>   File "/Users/bryan/Documents/koowalla-backend/app/venv_pypy/site-packages/falcon/routing/compiled.py", line 69, in insert
>     raise ValueError('The URI template for this route '
> ValueError: The URI template for this route conflicts with another route's template.

For some reason the route that is failing is the route after the previous one

    app.add_route('/v/{video_uuid}/likes',   endpoints.LikingUsersByVideoEndpoint())

So changing the variable name from `video_uuid` --> `video_uuid_or_short_id` causes the _following_ route to fail.

**Comment by painterjd** [comment]
Taking a look...

**Comment by kespindler** [comment]
@bcattle or @painterjd Did you ever resolve or determine the root cause of this bug?

**Comment by kgriffs** [comment]
Unfortunately this is a leaky abstraction based on the router implementation. Adding `/v/{video_uuid_or_short_id}` overwrites the previous route for `/v/{video_uuid}`, so now there is just one route, `/v/{video_uuid_or_short_id}`. Then, attempting to add `/v/{video_uuid}/likes` causes a conflict because different names are used at the same level in the path hierarchy.

The workaround is to use the same field name at that level in the path, instead of a different one, e.g.:

```
/v/{video_uuid_or_short_id}
/v/{video_uuid_or_short_id}/likes
```

The router compiles the collection of routes into a tree, assigning field values as it works its way down. To support different names at a given node in the tree, it would need to store them under an intermediate/temporary field name until the traversal was complete. Then it would know what the field name should be, and it could assign the values to their final keys. We'd have to experiment with that (happy to take a look at a PR along these lines) to see if it can be done without significantly impacting performance. 

At the very least we should improve the error message.

**Comment by bcattle** [comment]
Ah thanks @kgriffs for the explanation. That makes sense.

**Comment by kgriffs** [comment]
consolidating into #663
