### ISSUE TITLE
TestCase wrongly unquotes

### ISSUE THREAD

**Issue by masellfoodpanda** [falconry/falcon#826]
According to specs https://www.python.org/dev/peps/pep-3333/#id39 only quote/unquote is used by uwsgi, this means that this is wrong: https://github.com/falconry/falcon/blob/master/falcon/util/uri.py#L221
patch for tests

```
index fef8bec..b958dbe 100644
--- a/tests/test_utils.py
+++ b/tests/test_utils.py
@@ -190,6 +190,7 @@ class TestFalconUtils(testtools.TestCase):
                          u'This thing is \u00e7\u20ac')

         self.assertEqual(uri.decode('ab%2Fcd'), 'ab/cd')
+        self.assertEqual(uri.decode('as+df'), 'as+df')

         self.assertEqual(uri.decode('http://example.com?x=ab%2Bcd%3D42%2C9'),
                          'http://example.com?x=ab+cd=42,9')
```

**Comment by ueg1990** [comment]
According to the docstring for function decode in util/uri.py, the function is trying to model urllib.parse.unquote_plus which replaces '+' with ' ' (spaces).

**Comment by ueg1990** [comment]
Also, the decode function that you referred to in uri.py is only used for parsing query strings (https://github.com/falconry/falcon/blob/master/falcon/util/uri.py#L249) and according to https://en.wikipedia.org/wiki/Query_string, '+' is valid inside a query string and maps to spaces when decoding. This is my opinion

**Comment by masellfoodpanda** [comment]
The thing is, that this decode function is also used in the TestBase. Were it is not doing the same thing as a uWSGI would do.

**Comment by kgriffs** [comment]
Hi @masellfoodpanda, I don't think I quite follow what you are saying. When it comes to query strings, uWSGI does not decode them, but passes them raw through the WSGI environ dict. Falcon's framework also does not decode the query string, but passes it along unchanged to `falcon.API.__call__()`. At this point, the value is passed into `falcon.Request.__init__()` where it is finally decoded via `uri.decode()`. 

uWSGI isn't doing any decoding here, so I don't know what you mean by the framework "not doing the same thing as a uWSGI would do." Could you please clarify?

FWIW, `uri.decode()` currently interprets the plus sign as a space since it is not uncommon for HTTP clients to use '+' instead of '%20' in query strings.  This is due to the history of query strings being intertwined with that of `application/x-www-form-urlencoded`, which specification actually recommends encoding spaces with the plus sign.

**Comment by kgriffs** [comment]
Please let me know if this is still an issue and we'll reopen.
