### ISSUE TITLE
Better way to get the port from the request?

### ISSUE THREAD

**Issue by EmilStenstrom** [falconry/falcon#835]
I'm in the process of porting an old bottle app to falcon. The first thing my app does is generate some api documentation and returns it as HTML. In the documentation I have clickable links that makes it easy to explore the api. Whether on localhost or on production I want the links to work, so I generate a "site" parameter that I prefix all links with. 

In bottle this was: 

``` python
site = "%s://%s" % (request.urlparts.scheme, request.urlparts.netloc)
```

In falcon the easiest way I can find to do this is

``` python
site = "%s://%s" % (request.protocol, request.headers["HOST"])
```

**Having to rely on manually reading the HOST header feels very inelegant to me**. Note that this is not the same as `request.host` which returns the host without the port number.

I see a couple of ways this can be improved:
1. Make `request.host` include the port in the response. Backwards incompatible, even though everyone that previously relied on port numbers probably didn't use request.host anyway.
2. Add new property `request.host_with_port`.
3. Add new property `request.port` and let people that need the host + port combination write their own utility that combine it with the host.

I'm willing to write a pull request for this, but would love some feedback on which of the versions you would prefer.

**Comment by kgriffs** [comment]
Hi @EmilStenstrom, thanks for bringing this up. To improve parity with other libraries/frameworks, I propose making all three of the following changes:

* Add a new property, `Request.port`.
* Add a new property, `Request.netloc` that will contain the host as well as the port (if present). Note that "netloc" is consistent with the standard library's `urlparse()`. The value can be taken directly from the WSGI variables 'HTTP_HOST', or 'SERVER_NAME' and 'SERVER_PORT' (use the latter variables when 'HTTP_HOST' is missing. See also: https://www.python.org/dev/peps/pep-3333/#url-reconstruction).
* Add a new property, `Request.scheme` and convert `Request.protocol` into a deprecated alias of the new property (honestly, I don't remember why "protocol" was used in the first place, since that isn't the standard term). 

Does that sound reasonable?

**Comment by EmilStenstrom** [comment]
Hi! All your suggestions sound good to me. Thanks for listening!

**Comment by EmilStenstrom** [comment]
Thanks! ❤️
