### ISSUE TITLE
Add support for query string parameters in route templates

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#838]
We can borrow from RFC 6570 syntax and do something like this:

``` py
'/things{?count,detailed}'
```

Note that all params would default to None if present. I'm assuming we would just pass these as kwargs to the responder method.

Filters could be specified by extending RFC 6570, i.e:

``` py
'/things{?count:int,detailed:bool}'
```

**Comment by softgripper** [comment]
This is EXACTLY what I'm after.

I'm basically making my own server that wraps an external API, but does some processing on some of the functions, and is accessed by ajax so need to avoid CORS and my own caching.

I've added a route decorator and basically do this.

```
@route('/market/{instrument}/{currency}/trades?since={timestamp}')
class Trades(RoutedHandler):
     def __init__(self):
         super().__init__()
```

Then the URL I use in the super is

```
    def on_get(self, req, resp, **kwargs):
        result = requests.get(config.domain + self.route.format(**kwargs))
        resp.body = result.text
```
Of course the 'timestamp' param in the above example does not get passed, but for all simple "/" param based API calls, it's saved me a LOT of time and effort, and is quite elegant.

I wish I knew how to work around this, but I've only been using Falcon since yesterday. 👍

**Comment by vytas7** [comment]
Given this has generated only a limited interest from the community, I think we want to keep the default router focused solely on routing based on `req.path`. However, I filed a separate issue to be able to easier extend the default router with additions like this one.
