### ISSUE TITLE
Unit test failure when building 1.0.0 Debian package in Sid

### ISSUE THREAD

**Issue by thomasgoirand** [falconry/falcon#845]
When building the Debian package of python-falcon 1.0.0 in Sid, I get the below failure:

======================================================================
FAIL: tests.test_req_vars.TestReqVars.test_client_accepts
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/home/zigo/sources/openstack/newton/python-falcon/build-area/python-falcon-1.0.0/tests/test_req_vars.py", line 300, in test_client_accepts
    self.assertFalse(req.client_accepts('application/xhtml+xml'))
  File "/usr/lib/python2.7/dist-packages/unittest2/case.py", line 696, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false

I disabled this unique fail (through debian/patches/disable-failing-test.patch), and uploaded that to Debian Experimental, until this can be solved upstream. Please help me to fix this.

**Comment by kgriffs** [comment]
Hi @thomasgoirand, thanks for the report. That error is probably the result of installing the `mimeparse` package, instead of the `python-mimeparse` package. The latter is a better-maintained fork, and includes several bug fixes. `python-mimeparse` is the one that falcon's setup.py references. I may need to start vendoring it to avoid this problem in the future.

**Comment by kgriffs** [comment]
Going to go ahead and close this. Please reopen if you weren't able to resolve the problem.
