### ISSUE TITLE
How to *disable* Transfer-Encoding: chunked?

### ISSUE THREAD

**Issue by nicolinux** [falconry/falcon#912]
I'd like to not have Falcon use chunked transfer encoding and set the Content-Length myself for a response header. I have tried to set and unset resp.stream_len but I still get chunked encoding.

**Comment by nicolinux** [comment]
Wrong channel for asking questions. Better do it here:
https://groups.google.com/forum/#!forum/falconframework

Hm on the other hand, the google group is empty... Ok, so I am reopening here.

**Comment by kgriffs** [comment]
Hi @nicolinux, we just started using the google group, so feel free to post there. Regardless, re your question, the framework never attempts to set `Transfer-Encoding` since PEP-3333 forbids WSGI apps from setting hop-by-hop headers. When req.stream_len is not set, the framework will omit `Content-Length` from the response, which usually causes the WSGI server to chunk the response.

**Comment by nicolinux** [comment]
Ok, thanks for the answer. I still don't have success with it. I have posted an updated question on the new Google group:
https://groups.google.com/forum/#!topic/falconframework/VRFeNCkfK4o

**Comment by nicolinux** [comment]
Ok found the problem. It is not related to Falcon or Gunicorn. Nginx drops the Content-Length header if gzip is enabled because it compresses on the fly and thus can't know the file size beforehand. It then automatically adds Transfer-Encoding: chunked.
