### ISSUE TITLE
uwsgi, transformation_gzip and the content-length header

### ISSUE THREAD

**Issue by gregj1** [falconry/falcon#950]
I have a falcon instance running under uwsgi and nginx. I have enabled the gzip transformation to shrink responses sent from the falcon app.

After enabling this configuration, my application stops working. The network tab in chrome's developer tools shows the api requests as "incomplete". The response header shows the Content-Length of the uncompressed response.

Notes in [a ticket](https://github.com/unbit/uwsgi/issues/822) in the uwsgi repo suggest that this is caused by the application sending a Content-Length header. I can't see any clear way to have uwsgi override the header.

The application works again if I modify the falcon source to prevent it sending content-length at api.py line 682:
```python
        #
        # Set status and headers
        #
        if req.method == 'HEAD' or resp.status in self._BODILESS_STATUS_CODES:
            body = []
        else:
            body, length = self._get_body(resp, env.get('wsgi.file_wrapper'))
            if length is not None:
                #resp._headers['content-length'] = str(length)
                pass
```

Is falcon not sending a content-length a reasonable situation? If so I'm happy to clean this up into an optional setting and send a pull request.

uwsgi configuration:
```
...
plugins = python3,transformation_gzip
response-route-if = contains:${HTTP_ACCEPT_ENCODING};gzip gzip:
response-route-run = last:
...
```

- uwsgi: 2.0.12-debian
- falcon: 1.1.0
- nginx: 1.10.0

**Comment by vytas7** [comment]
Hi @gregj1 !
And sorry for somewhat delayed response (only 3 years... :grimacing: )

I'm afraid not setting the `Content-Length` header (when it is known) sounds suboptimal. It is not unreasonable _per se_, but setting `Content-Length` when you know it should not put you at disadvantage.
Without knowing the details, I would first of all suspect a bug in the mentioned uWSGI plugin. It might be worth rechecking with 2.0.18 (the latest version at the time of writing).

If I was given your application/server stack, I would first of look into enabling [compression in Nginx](http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip). I have gone that way in some projects and Nginx seems to do the right thing™. The response is streamed through the compression filter, the `Content-Length` header is removed, and chunked transfer encoding is used.

If that doesn't help, you can easily force Falcon & WSGI to stream the response by setting [`Response.stream`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.stream) to an iterable:
```
resp.content_type = falcon.MEDIA_TEXT  # Or any other media type
resp.stream = [b'My data']
```

I'm closing this since it is a really old issue hoping you have probably resolved it one or another way, but do not hesitate to reopen if the discussion is still of interest.
