### ISSUE TITLE
Add an option to keep a trailing slash in the request path

### ISSUE THREAD

**Issue by roeih-stratoscale** [falconry/falcon#966]
Right now in the "Normalize path" section in request.py, a trailing slash, if exists, is stripped from the request path (this was done as part of https://github.com/falconry/falcon/issues/48).
I suggest to make this stripping configurable by adding an option to RequestOptions, something like keep_url_path_trailing_slash (default True, as it is now), in order to allow to avoid stripping the trailing slash.

My use-case is developing an AWS-compatible S3 object store service. The AWS authentication uses the URL path as part of the signature calculation (see e.g. (http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html, item 3) and it's impossible to calculate the correct signature if the trailing slash is stripped...
Others might benefit from this option too.

I checked such a simple fix in my environment and it seems to work. If there isn't anything problematic I'm missing, it might be beneficial to add it to the main branch.
WDYT?

**Comment by androiddrew** [comment]
Sounds like you should submit a pull request.

**Comment by jmvrbanac** [comment]
@roeih-stratoscale Thank you for bring this up and providing a great use-case for adding in this capability! As it sounds like you’ve already made some effort in putting together a fix, it would be awesome to see that in a PR. If you don’t have the time at the moment that's perfectly fine. This change sounds like a great starter project as well, so I’m sure someone else in the community could pick it up as well. Anyhow, just let folks know if you intend on working on this yourself so that we don't have folks doing duplicate work.

**Comment by roeih-stratoscale** [comment]
@jmvrbanac, I just wanted to know if this enhancement is interesting to anyone.Now that I know it is, I'll open a PR.

**Comment by hoylen** [comment]
+1 since keeping the slash is important for signatures in OAuth 1.0 too. Not to mention someone might make the absence or presence of a trailing slash significant to their application.

I wonder if it would be better if the default behaviour should be to keep the slash, and the option is there to remove it? Obviously that would be a breaking change in behaviour, so happy with either behaviour.

**Comment by kgriffs** [comment]
Thanks everyone, this is good feedback. We can look into changing the default for 2.0, but until then we'll need to avoid making any breaking changes.

**Comment by kgriffs** [comment]
Fixed in #972
