### ISSUE TITLE
Proposal: pass request object to router.find

### ISSUE THREAD

**Issue by sseg** [falconry/falcon#967]
It can be useful to make decisions about headers in the routing layer (e.g. for API versioning or media types). Having the full request available to the router allows the application to route requests based on any value of the WSGI request env.

To implement this kind of functionality currently requires putting routing logic into response handlers (after HTTP method resolution) or manipulating the request URI using middlewares. Neither of these solve the problem in a straightforward way, and both overload another layer of the application with values computed from headers (respectively the response handler and the request path).

`falcon.api.API`'s `_get_responder` method should pass the request object to the router during route-finding to provide greater control in the routing process:
```python
route = self._router.find(path, request=req)
```

This would constitute a breaking change in the routing API, where the `find` methods of routers would need to accept a new keyword argument, but I believe the power this affords makes it worth the change. I expect the biggest win from this change would be in allowing applications to solve API versioning (https://github.com/falconry/falcon/issues/645, https://github.com/falconry/falcon/issues/932) using a custom router or a router wrapper.

What do you think?

**Comment by kgriffs** [comment]
Hmm, interesting idea. Since `path` is simply `req.path`, you might just pass in `req` instead, e.g.:

```py
route = self._router.find(req)
```

If we make this a breaking change, it will have to wait for 2.0. Alternatively, we could introduce a new method that, if present, is called instead of find(), e.g.:

```py
if self._router_implements_search:
    route = self._router.search(req)
else:
    route = self._router.find(path)
```

Alternatively, we could wrap `find()` with a shim when `search()` is not available, or use it directly when it is. This would incur the overhead of an extra function call in the former case:

```py
    route = self._router_search(req)
```

Finally, we could avoid introducing a new method by simply adding a kwarg as originally proposed. We could check the argspec to determine whether or not the router supports the new parameter. But those two args would be somewhat redundant as I mentioned earlier.

**Comment by sseg** [comment]
I'm in favour of branching within `_get_responder` as it reads simply and introduces very little overhead for both the default router and those implementing the new method. 

There's a risk that whichever name is chosen for the new method could already be used in the namespace of a user's custom router. We could introduce a new keyword argument to the API class that allows users to specify which method on their router accepts a Request object (if any), defaulting to `"search"`.

**Comment by sseg** [comment]
This issue is resolved with: https://github.com/falconry/falcon/commit/ad583b9e170361bbc6258997ff11c69bc8ac081f, https://github.com/falconry/falcon/commit/572d3ac90792ec4751fae946126cb718bc221c36, https://github.com/falconry/falcon/commit/ee89b7c9ffcd373900a8c3e8090c6ed90e1f4631
